### ISSUE TITLE
Editor plugin already added for class: JoltEditorPlugin

### ISSUE THREAD

**Issue by hyouuu** [godot-jolt/godot-jolt#1011]
Updated from 0.12 to 0.14 by downloading the folder and override the previous one (install from Asset Lib doesn't seems to actually do the upgrade as the console still warns 0.12 not supporting Godot 4.3)

Then upon starting Godot see this warning `Editor plugin already added for class: JoltEditorPlugin`

**Comment by mihe** [comment]
Apologies for taking so long to triage this, but I don't seem to be able to reproduce this issue. Overwriting the files from 0.12.0-stable with the ones from 0.14.0-stable results in a correct loading with no warnings for me.

> Then upon starting Godot see this warning `Editor plugin already added for class: JoltEditorPlugin`

Are you still seeing this warning? If so, is the warning resolved if you just delete your `addons/godot-jolt` folder and extract the latest version of it again? If that doesn't help I'd be curious to know what OS you're running on.

> install from Asset Lib doesn't seems to actually do the upgrade

There is indeed no update mechanism in the Godot Asset Library currently.
