### ISSUE TITLE
`intersect_shape` sometimes omits expected contacts

### ISSUE THREAD

**Issue by Griiimon** [godot-jolt/godot-jolt#1014]
Is this a known feature/setting/issue where the max_result parameter of `intersect_shape()` is ignored if it's set manually to higher than the default 32?
I'm encountering this in a custom double-precision v4.3 build, GodotPhysics handles it correctly..

I thought I asked before creating a MRP, but will be happy to do so

**Comment by mihe** [comment]
I just tried this for myself, and it seems to work fine. If I do an `intersect_shape` overlapping 40 bodies I end up with 40+ hits.

**Comment by Griiimon** [comment]
I managed to reproduce it in v4.3, even without the double-precision build.

[MRP](https://github.com/Griiimon/jolt-intersect-shape-bug)

I'm spawning a lot of collision shapes in a 9x9 grid under the same physics body. The correct output would be 82, which includes the original shape that I cloned 81 times.
This works as expected with GodotPhysics, but switching to Jolt and everything else being the same the output is 69. 

I don't know if that helps: in my game where I encountered this bug originally it seemed like there was always one and the same quadrant of the sphere missing, a continious region where it didn't detect any shapes.

**Comment by mihe** [comment]
Hm, yeah, this is definitely weird.

If I switch to creating multiple `StaticBody3D` instead of multiple shapes in a single body, then I still see the same thing, but if I switch to creating multiple `RigidBody3D` instead, without touching their layer/mask/exceptions, meaning they instantly repel eachother, then I do in fact get at least one hit per body so long as the query shape is big enough. But if I _do_ clear their collision masks and set their gravity scale to 0, then I see the same behavior as with multiple shapes (and multiple `StaticBody3D`).

I'll see about recreating this in Jolt's `Samples` application.

**Comment by mihe** [comment]
Oh, it's because of `physics/jolt_3d/collisions/use_enhanced_internal_edge_removal`.

That could potentially explain the case of multiple shapes, but it doesn't explain the case of multiple `StaticBody3D`, since it's not supposed to work cross-body.

**Comment by Griiimon** [comment]
> Oh, it's because of `physics/jolt_3d/collisions/use_enhanced_internal_edge_removal`.
> 
> That could potentially explain the case of multiple shapes, but it doesn't explain the case of multiple `StaticBody3D`, since it's not supposed to work cross-body.

Interesting! That answers one but also raises another question: With my perfectly aligned grid, why are only certain internal edges removed? 
For me, having this setting enabled and working properly is even more valuable since I'm making a Space Engineers clone with potentially very large grids and I'd love the physics engine optimizing them into just a few big colliders internally.
Doing a manual, non-physics intersect_shape() check on my BlockGrids I could live with.


At least this its consistent: If I remove all the collision shapes that were detected by `intersect_shape` it will always leave this region in the lower right quadrant of the sphere..

![intersect region](https://github.com/user-attachments/assets/3ef1629b-4b8b-4dc5-be68-1723d31c8af9)


Btw, after I change the `use_enhanced_internal_edge_removal` settings my program will just fail silently when I run it. It doesn't even get to the `print` statement and simply quits without any warning. Every time I change the setting I have to reload the project.

**Comment by mihe** [comment]
@jrouwe As I'm testing this in `Samples` I'm starting to question whether I misunderstood the thing about `InternalEdgeRemovingCollector` not being able to do cross-body removals, which was mentioned [here](https://github.com/jrouwe/JoltPhysics/issues/717#issuecomment-1902167381) (and I believe elsewhere that I can't find right now).

<details><summary><code>SimpleTest.h</code></summary>
<p>

```cpp
#pragma once

#include <Tests/Test.h>

class SimpleTest : public Test
{
public:
    JPH_DECLARE_RTTI_VIRTUAL(JPH_NO_EXPORT, SimpleTest)

    virtual void Initialize() override;
};
```
</p>

</details>
<details><summary><code>SimpleTest.cpp</code></summary>
<p>

```cpp
#include <TestFramework.h>

#include <Tests/General/SimpleTest.h>
#include <Jolt/Physics/Body/BodyCreationSettings.h>
#include <Jolt/Physics/Collision/CollisionCollectorImpl.h>
#include <Jolt/Physics/Collision/InternalEdgeRemovingCollector.h>
#include <Jolt/Physics/Collision/Shape/BoxShape.h>
#include <Jolt/Physics/Collision/Shape/SphereShape.h>
#include <Layers.h>

JPH_IMPLEMENT_RTTI_VIRTUAL(SimpleTest)
{
    JPH_ADD_BASE_CLASS(SimpleTest, Test)
}

void SimpleTest::Initialize()
{
    constexpr float box_half_size = 0.5f;
    constexpr float box_size = box_half_size * 2.f;
    constexpr int box_count = 2;
    constexpr float box_start = (float)box_count / 2.f * -box_size + box_half_size;

    RefConst<Shape> box_shape = new BoxShape(Vec3(box_half_size, box_half_size, box_half_size));

    for (int x = 0; x < box_count; x++) {
        for (int z = 0; z < box_count; z++) {
            const float pos_x = box_start + box_size * x /*+ x * 0.001f*/;
            const float pos_z = box_start + box_size * z /*+ z * 0.001f*/;
            mBodyInterface->CreateAndAddBody(BodyCreationSettings(box_shape, RVec3(pos_x, 0, pos_z), Quat::sIdentity(), EMotionType::Static, Layers::NON_MOVING), EActivation::Activate);
        }
    }

    RefConst<Shape> sphere_shape = new SphereShape(100.0f);

    CollideShapeSettings collide_settings;
    collide_settings.mActiveEdgeMode = EActiveEdgeMode::CollideWithAll;
    collide_settings.mCollectFacesMode = ECollectFacesMode::CollectFaces;

    AllHitCollisionCollector<CollideShapeCollector> collector;
    InternalEdgeRemovingCollector ier_collector(collector);
    mPhysicsSystem->GetNarrowPhaseQuery().CollideShape(sphere_shape, Vec3::sReplicate(1.0f), RMat44::sIdentity(), collide_settings, Vec3::sZero(), ier_collector);
    ier_collector.Flush();

    Trace("Hit count: %d", collector.mHits.size());
}
```
</p>

</details> 

That test very clearly culls hits between different bodies.

Was the comment linked above talking about this purely from the perspective of the collision detection that happens within the simulation perhaps, and `InternalEdgeRemovingCollector` does in fact cull across bodies as well if you're just doing a simple narrow-phase query like this? If so, then me having this be project setting be global across both bodies and queries (while also enabled by default) was probably not a great idea.

Ideally you'd be able to toggle this a per-query basis I guess, but unfortunately there is no mechanism for custom query parameters in Godot right now.

> With my perfectly aligned grid, why are only certain internal edges removed?

That I don't know. I imagine it's probably some quirk of the algorithm. Maybe it makes sense to @jrouwe.

> I'd love the physics engine optimizing them into just a few big colliders internally

Note that in this context the enhanced internal edge removal is not an optimization. You're still doing the same amount of collision detection as you would with it disabled, but with an added step that goes through and culls edge hits.

> Btw, after I change the `use_enhanced_internal_edge_removal` settings my program will just fail silently when I run it. It doesn't even get to the `print` statement and simply quits without any warning. Every time I change the setting I have to reload the project.

I don't seem to be able to reproduce this. It shouldn't really be possible in the first place. Reloading the project has no bearing on anything regarding the project settings in the game process.

**Comment by jrouwe** [comment]
> If so, then me having this project setting be global across both bodies and queries (while also enabled by default) was probably not a great idea.

Without looking into much detail (because I'm a bit short on time), the `InternalEdgeRemovingCollector` currently requires calling `Flush` between bodies. If you use it with a `NarrowPhaseQuery` like above, the `Flush` function won't be called and it will indeed incorrectly cull things. `CharacterVirtual` does this by [implementing its own narrow phase collision detection](https://github.com/jrouwe/JoltPhysics/blob/d6e015372b08f28c3c62e9aaab9a5cb2af667e54/Jolt/Physics/Character/CharacterVirtual.cpp#L360-L418). Maybe I should move this function to `NarrowPhaseQuery` so that everyone can use it. Can you check if your problems go away if you copy paste that bit of code?

**Comment by mihe** [comment]
> If you use it with a `NarrowPhaseQuery` like above, the `Flush` function won't be called and it will indeed incorrectly cull things.

Right. That's not good. I didn't realize this was a hard requirement for it to function correctly.

> Can you check if your problems go away if you copy paste that bit of code?

That does solve the problem when using multiple bodies.

I guess the fix here is to copy what that code does, or make use of what you talked about exposing, in order to solve the only real bug here, and then I guess it would also make sense to split this `use_enhanced_internal_edge_removal` project setting into three different settings, one for bodies, one for queries (like `intersect_shape`) and one for kinematic movement (`body_test_motion`), so that I can leave the one for queries disabled by default.

**Comment by jrouwe** [comment]
> I guess the fix here is to copy what that code does, or make use of what you talked about exposing

I will add a new function on NarrowPhaseQuery that does his.
