### ISSUE TITLE
Error "godot-jolt_windows-x64_editor.pdb' does not exist." in Godot console on load

### ISSUE THREAD

**Issue by fhgaha** [godot-jolt/godot-jolt#1016]
Godot 4.3 stable console version.
Windows 10.

### Steps to reproduce:
1. Load Godot with console, notice no error messages.
2. Go to AssetLib tab in Godot editor, search for "Godot Jolt", download.
3. Request to restart appears, press "Save and restart"
4. Notice bunch of errors in Godot console, understandable, unrealed to the issue.
5. Reload Godot again. In Godot console notice error message. In my case it's 
```
ERROR: File 'D:\MyProjects\Godot\Godot 4\water_slides_godot\godot-jolt\windows/godot-jolt_windows-x64_editor.pdb' does not exist.
   at: (platform/windows/windows_utils.cpp:158)
WARNING: Failed to rename the PDB file. The original PDB file for 'D:\MyProjects\Godot\Godot 4\water_slides_godot\godot-jolt\windows/~godot-jolt_windows-x64_editor.dll' will be loaded.
     at: open_dynamic_library (platform/windows/os_windows.cpp:410)
```
This error message will appear on every Godot load since now. No errors in Godot output tab. No tool code is running.

### This might help
In case you want small reproduction project you can use my repository I'm working on. Specifically [this ](https://github.com/fhgaha/water_slides_godot/commit/189ff5344eedcca37cdc8b5617f243d045ffc889) commit before installing Godot Jolt and [this ](https://github.com/fhgaha/water_slides_godot/commit/9a085e6513f67719095408be06700dc9eaeb9cf0)commit after, with error.

**Comment by mihe** [comment]
This is/was a bug Godot 4.3-stable itself, which has since been fixed and will be included in the upcoming Godot 4.3.1 release: godotengine/godot#96350

You can work around it for now by downloading the debug symbols ZIP from the release [here on GitHub](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.14.0-stable) and extracting it alongside the extension libraries.

**Comment by samdeane** [comment]
Is there an option to have the pdb files copied along with the DLLs, as part of `cmake --install build/windows-msvc-x64 --config EditorDistribution --prefix C:/Path/To/Project`.

If not, that would be a helpful addition.

**Comment by mihe** [comment]
Yes, just pass `-DGDJ_INSTALL_DEBUG_SYMBOLS=YES` when generating the build directory, and you'll get the debug symbols when installing.
