### ISSUE TITLE
Add functions to apply forces/impulses to `SoftBody3D` objects and vertices thereof

### ISSUE THREAD

**Issue by James103** [godot-jolt/godot-jolt#1027]
Currently, there is no way I know of to apply a force or impulse to a `SoftBody3D` object or individual vertices thereof. If there was, it would enable fine-grained control over `SoftBody3D` objects.

For example, one could use this feature to make blobs which move on their own, drapes or other cloths which fold and unfold on their own, or capes/kites/etc. which drag their attached bodies around.

Specifically, I want to have the following functions implemented for `SoftBody3D`:
```
void apply_central_force(force: Vector3)
void apply_force(force: Vector3, point_index: int)
void apply_central_impulse(impulse: Vector3)
void apply_impulse(impulse: Vector3, point_index: int)
```

See also https://github.com/godotengine/godot-proposals/issues/1013.

**Comment by mihe** [comment]
As mentioned in #1026, this extension is moving towards becoming an engine module in Godot itself instead. As such, I have no plans to add to the current interface of this extension.
