### ISSUE TITLE
Godot Physics feature parity

### ISSUE THREAD

**Issue by mihe** [godot-jolt/godot-jolt#117]
## Description

This issue is meant to serve as a high-level overview of the things that need to be implemented in order to reach feature parity with Godot Physics.

Note that the issues listed below will likely remain open for a while, even after their respective features are fully implemented, so make sure to check within them for details on progress.

## Objects

- [x] #95
- [x] #92
- [x] #93
- [x] #114
- [x] #94
- [x] #159
- [x] #160

## Shapes

- [x] #96
- [x] #97
- [x] #98
- [x] #99
- [x] #100
- [x] #101
- [x] #102
- [x] #103
- [x] #104
- [x] #105

## Joints

- [x] #106
- [x] #107
- [x] #108
- [x] #109
- [x] #110

## Other

- [x] #111
- [x] #112
- [x] #113

**Comment by Salvakiya** [comment]
This is a very comprehensive list. Great work!

**Comment by mihe** [comment]
Although there are some minor things in these issues to sort out still, they have largely served their purpose and have now been closed.

Any remaining work has had new issues created for it.

Also, you can now try these things out for yourself using the [release](https://github.com/godot-jolt/godot-jolt/releases/latest) that I just pushed here on GitHub. Be sure to report any bugs or other weird issues you run into, no matter how seemingly insignificant.

Thank you! 🙏

**Comment by KiwwiPity** [comment]
there exists a possibility to upload this to Godot Asset repository?

**Comment by mihe** [comment]
Yes, I've been meaning to look into adding it to the Godot Asset Library, but haven't gotten around to it yet.

I'll see about adding it after I publish 0.2.0 in the next couple of days.
