### ISSUE TITLE
No support for 32-bit x86 platforms

### ISSUE THREAD

**Issue by mihe** [godot-jolt/godot-jolt#27]
To align with Godot's platform support on at least the desktop platform we need 32-bit x86 builds for both Windows and Linux.

While the Windows part of this should be a breeze, with their WoW64 stuff, I'm not all that familiar with compiling 32-bit applications on 64-bit Linux, so that might require some investigation.

**Comment by jrouwe** [comment]
Can't you just compile Jolt in 32 bit mode (see cmake_vs2022_cl_32bit.bat)? I have only tested 32 bit mode on Windows but I think it should compile on Linux too.
