### ISSUE TITLE
Crash on unloading a scene with a Rigidbody inside an Area3D

### ISSUE THREAD

**Issue by tutasmaster** [godot-jolt/godot-jolt#298]
I've tested this in quite a few scenarios, and it looks like there is a consistent crash that happens whenever there is an active, unfrozen rigidbody overlapping an Area3D node, and I change/reload the scene through `get_tree().reload_current_scene()` or `get_tree().change_scene_to_file("otherScene.tscn")` regardless of what other scene gets loaded.

So far I've worked around this by moving the rigidbody away from the area, then waiting for a new iteration of `_physics_process()` before changing the scene.

This is happening in Godot 4.0 with godot-jolt compiled with msvc-x64. I do not have any error logs as far as the editor is concerned, it just crashes the game and not the editor.

**Comment by mihe** [comment]
Thank you for reporting this.

I suspect this might be a regression caused by #280.

I'll look into it tomorrow.

**Comment by mihe** [comment]
Well, it was indeed a regression, but caused by #282 as part of some overly aggressive cleanup. Reloading/changing scenes should work fine now. Hopefully it didn't cause you too much trouble.

Thanks again for reporting the issue.
