### ISSUE TITLE
`StaticBody3D` does not support constant velocities

### ISSUE THREAD

**Issue by mihe** [godot-jolt/godot-jolt#331]
Originated from #92.

The [`constant_linear_velocity`](https://docs.godotengine.org/en/4.0/classes/class_staticbody3d.html#class-staticbody3d-property-constant-linear-velocity) and [`constant_angular_velocity`](https://docs.godotengine.org/en/4.0/classes/class_staticbody3d.html#class-staticbody3d-property-constant-angular-velocity) properties on `StaticBody3D` are not currently feasible to implement due to Jolt not offering anything equivalent to this, nor allowing any way of modifying contact velocities.

There's currently an open issue about it here: jrouwe/JoltPhysics#516

**Comment by jrouwe** [comment]
Can you take a look at jrouwe/JoltPhysics#551? I think with this you can implement this functionality.

**Comment by mihe** [comment]
Works like a charm!

https://github.com/godot-jolt/godot-jolt/assets/4884246/6caf5812-e7fb-459a-b154-6053f5272981

**Comment by mihe** [comment]
For reference, here's what the exact same scene looks like in Godot Physics:

https://github.com/godot-jolt/godot-jolt/assets/4884246/1e12a4c1-5b3f-46a3-a2b2-fafc2af5e26b

I'm not sure what to make of the boxes having much smoother transitions when crossing between the conveyor belts. I assume it's catching the edges of the bodies in Jolt due to a lack of cross-body welding?

**Comment by jrouwe** [comment]
Yes, it's colliding with the edges. I see a little bit of that in the Godot simulation as well. Jolt allows objects to sink into the geometry a bit (PhysicsSettings::mPenetrationSlop) and the speculative contacts (PhysicsSettings::mSpeculativeContactDistance) also cause more edge collisions. Setting them both to zero makes most of these ghost collisions go away (at a slight performance cost).

**Comment by mihe** [comment]
I'm struggling a bit with replicating Godot's behavior when it comes to `constant_angular_velocity`.

Am I correct in assuming that replicating something like this, where the platform has a `constant_angular_velocity` of 36 degrees per second around the Y-axis, and the box is perfectly centered over the platform's center-of-mass, isn't possible with only something like `mRelativeSurfaceVelocity`?

https://github.com/godot-jolt/godot-jolt/assets/4884246/eabc893d-6c72-44b6-a297-82f5ebd83160

**Comment by jrouwe** [comment]
You're right that with a body perfectly centered on the rotation axis, it won't work. You will need to be able to specify a surface velocity per contact point rather than per manifold (I didn't implement this because it would need much more memory). When the body is further away from the center of rotation you can approximate the result:

```relative_surface_velocity = constant_linear_velocity + constant_angular_velocity cross (average_contact_point - center_of_mass)```

**Comment by mihe** [comment]
Alright. That's perfectly fine. As long as I wasn't missing something obvious.

I made a few attempts at incorporating the manifold, but I wasn't quite sure which was correct. I'll go ahead with the average contact point then.

Thank you!

**Comment by jrouwe** [comment]
@mihe I added a new option to ContactSettings which should allow you to properly implement constant_angular_velocity

**Comment by mihe** [comment]
That's awesome, thank you! I'll take it for a spin shortly. :)

**Comment by mihe** [comment]
@jrouwe I'm noticing that the order in which you add bodies seem to affect which body becomes the one on which the other rotates. In your `ConveyorBeltTest` you can see this difference by creating the `mAngularBelt` body below the bodies that drop down onto it.

Is there a way I can control this somehow, or is there some obvious linear algebra that I'm completely missing?

**Comment by jrouwe** [comment]
You're right. I left out a term in the example. I've fixed it in e6a18ba5029a2b47c0d315e883ac9238cc64dca2.

**Comment by mihe** [comment]
Right, that makes sense.

It all seems to work as expected now, and seems to line up with how Godot Physics behaves, which is great.

Thanks again!

https://github.com/godot-jolt/godot-jolt/assets/4884246/f51e60bb-ad56-4b38-9f6e-82acddb4e118
