### ISSUE TITLE
Kinematic collision methods don't respect collision exceptions

### ISSUE THREAD

**Issue by Pingar5** [godot-jolt/godot-jolt#339]
Collision exceptions are working as expected for RigidBodies, but not for CharacterBodies. I have attached a minimal reproduction project below

[col-exception-minimal-reproduction.zip](https://github.com/godot-jolt/godot-jolt/files/11491796/col-exception-minimal-reproduction.zip)

P.S. thanks so much for making this extension, I just worked for like a month to convert my project to godot 4 and then found out how buggy their physics are for 3D. So this saved me a ton of work

**Comment by mihe** [comment]
You're absolutely right. More specifically it seems it's my implementation of `body_test_motion` (which powers things like `move_and_slide`) that doesn't take collision exceptions into account. This throws a wrench into some assumptions that I had made in the code, so I need to think about this for a little bit.

Thank you for providing the minimal reproduction by the way, much appreciated.

**Comment by mihe** [comment]
It should be fixed now.

Thank you for reporting the issue!
