### ISSUE TITLE
Add a node for Jolt's `DistanceConstraint`

### ISSUE THREAD

**Issue by mihe** [godot-jolt/godot-jolt#351]
Jolt's `JPH::DistanceConstraint` is described as:

> Will attach two bodies with a stick (removing 1 degree of freedom).

I figured since there's no real equivalent to this fairly basic constraint in Godot, without resorting to the more expensive 6DOF joint, it might be good to add this as `JoltDistanceJoint3D` or something.

This joint also allows for springy behavior using its frequency and damping properties, which can be useful for things like picking.

**Comment by ODtian** [comment]
This feature is very common in other engines but missing in godot, is this still planning in godot-jolt?

**Comment by mihe** [comment]
It's highly likely that this extension will be moved over to be an official Godot module in a not too distant future, so I will be focusing solely on stuff that helps close the gap with Godot Physics going forward, meaning this will likely not be worked on.

Your best bet is probably to create a Godot proposal instead.

**Comment by mihe** [comment]
As mentioned here already, this is very unlikely to be worked on at this point, so I'll go ahead and close this.
