### ISSUE TITLE
Add support for iOS

### ISSUE THREAD

**Issue by mihe** [godot-jolt/godot-jolt#353]
Title says it all, really. It would be a shame not to support a major platform like iOS when both Godot and Jolt supports it.

**Comment by jbromberg** [comment]
Are there any plans on when this integration will start?

**Comment by jbromberg** [comment]
Awesome. I'd be happy to donate if it would be helpful to you.

**Comment by mihe** [comment]
Apologies for taking so long to get to this.

I'll try to have a release candidate out in the next day or two, at which point I'd appreciate if any of you subscribers could test out the build for me. I'll ping this issue again once it's out.

**Comment by jbromberg** [comment]
I can test on device

**Comment by mihe** [comment]
You can find it in the newly released [0.10.0-rc1](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.10.0-rc1).

Note I don't put up release candidates on the Godot Asset Library, so that's the only place to get it for now.

Let me know how it works for you.

**Comment by mihe** [comment]
[0.10.0-stable](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.10.0-stable) has been released now, but I'll admit I still haven't tested these builds very extensively, so be on the lookout for any potential issues, especially potential performance issues where it might seem like Godot Physics runs better.

**Comment by sanform** [comment]
the iOS simulator build would be a nice have. Is there a chance this comes in the future?

**Comment by mihe** [comment]
I do technically have the ability to build for the iOS Simulator already, with the `macos-ios-simulator` configure preset and corresponding `macos-ios-simulator-*` build presets, but I haven't actually tried running those builds in the simulator myself.

The reason for not including them in the releases originally was because it seemed like Godot required that both the simulator and non-simulator builds were packaged into the same XCFramework as _statically_ linked libraries, which turned out to be a bit of a pain for me to support, as I currently distribute _dynamically_ linked libraries packaged in regular framework bundles. While you can technically package multiple dynamically linked libraries as a single XCFramework bundle on iOS, it isn't something that Godot's Xcode generation supports at the moment.

Since then I've learned that there's a Godot feature tag called `simulator` which you can supposedly use to pick between two separate XCFramework bundles, so it might be that it's as easy as building these simulator builds, naming them something different and adding them as a separate entry in the `godot-jolt.gdextension` files with the `simulator` feature tag.

However, this extension will likely be merged into Godot as an engine module fairly soon, which would presumably resolve this issue, so it's unlikely that I will work on this for the extension.

**Comment by sanform** [comment]
Thank you so much for your thorough response!
