### ISSUE TITLE
Add support for Android

### ISSUE THREAD

**Issue by mihe** [godot-jolt/godot-jolt#354]
Title says it all, really. It would be a shame not to support a major platform like Android when both Godot and Jolt supports it.

**Comment by MajorMcDoom** [comment]
Would just like to mention that Android support is what is needed for making standalone VR games with Jolt. Would super appreciate this one, as my VR game is pretty physics-dependent. 🙏

**Comment by mgrigajtis** [comment]
I would also like to see this happen, as my main target is usually the Meta Quest 2 (Android).

**Comment by IPlayKindred** [comment]
any updates on this?

**Comment by DigitalN8m4r3** [comment]
just read https://github.com/godot-jolt/godot-jolt/pull/663
so if android support is now merged in, why isnt this closed yet?

btw hell of a job there!!!
thank you

**Comment by mihe** [comment]
That PR brings in updates to Jolt itself, not this extension, which includes some fixes necessary for Android/iOS support.

But I am working on both Android and iOS support at the moment, with Android support being more or less done already, but I need to figure out some things related to iOS before I merge it. If everything goes well I'll hopefully have a release candidate out with support for both before the end of next week.

**Comment by IPlayKindred** [comment]
HOLY MOLY GOD BLESS

**Comment by mihe** [comment]
Apologies for taking so long to get to this.

I'll try to have a release candidate out in the next day or two, at which point I'd appreciate if any of you subscribers could test it on your device(s). I'll ping this issue again once it's out.

**Comment by DigitalN8m4r3** [comment]
> Apologies for taking so long to get to this. I know this has been a highly requested feature.
> 
> I'll try to have a release candidate out in the next day or two, at which point I'd appreciate if any of you subscribers could test it on your device(s). I'll ping this issue again once it's out.

thank you for the hard work and takin the time to do this, will forward this down to the vr/xr community and make sure to get more ppl onto testing

**Comment by IPlayKindred** [comment]
> Apologies for taking so long to get to this. I know this has been a highly requested feature.
> 
> I'll try to have a release candidate out in the next day or two, at which point I'd appreciate if any of you subscribers could test it on your device(s). I'll ping this issue again once it's out.

no problem man, glad its here now

**Comment by mihe** [comment]
You can find it in the newly released [0.10.0-rc1](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.10.0-rc1).

Note that I don't put up release candidates on the Godot Asset Library, so that's the only place to get it for now.

Let me know how it works for you. The only Android device I have access to is my OnePlus 8T running Android 13, so I'm curious to hear how it works on your devices.

**Comment by mihe** [comment]
It turned out that 0.10.0-rc1 was running with some compilation flags that weren't quite right, resulting in Jolt being compiled with no optimizations enabled. You'll find a new release here that will hopefully perform a lot better: [0.10.0-rc2](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.10.0-rc2)

**Comment by IPlayKindred** [comment]
god bless man

**Comment by mihe** [comment]
[0.10.0-stable](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.10.0-stable) has been released now, but I'll admit I still haven't tested these builds very extensively, so be on the lookout for any potential issues, especially potential performance issues where it might seem like Godot Physics runs better.
