### ISSUE TITLE
Add support for double-precision

### ISSUE THREAD

**Issue by mihe** [godot-jolt/godot-jolt#355]
This would add support for builds of Godot that use double-precision floating-point numbers, enabled by building Godot with `precision=double`, as opposed to the default single-precision.

This would allow for much bigger worlds.

**Comment by SlashScreen** [comment]
What is the obstacle for getting this done?

**Comment by mihe** [comment]
Like most things in the backlog it's just about me finding the time to sit down and actually do it.

**Comment by SlashScreen** [comment]
It's pretty simple, I can give it a crack if you want. It's just a matter of renaming all `float`s to `real_t`s. I did it for Terrain3D.

**Comment by mihe** [comment]
> It's just a matter of renaming all `float`s to `real_t`s.

Jolt itself is more conservative about its use of `double`, with only a few select API calls using its `RVec3` type, so that likely won't work without a lot of "implicit conversion loses floating-point precision" warnings. You can of course just explicitly cast everything to `float`/`double` where necessary, but I'd rather be similarly conservative in my approach to avoid cluttering the code like that, if possible.

There also needs to be some minor changes made to [my fork](https://github.com/godot-jolt/godot-cpp) of godot-cpp to accommodate for this.

But the actual code changes aren't that big of a deal. It's more a question of how I'm going to approach building it, verifying it (continuously) and distributing it (if at all).

With regards to building it, this most likely would need to end up being just a separate CMake option to be passed as part of the configure step, rather than adding new [build presets](https://github.com/godot-jolt/godot-jolt/blob/36fce2c5f686916dc2775d14dc59ae55d540ff10/CMakePresets.json#L368-L1367), since they're currently suffering from a brutal combinatorial explosion already.

As far as distributing it goes, I'm leaning more towards this just being a separate download on GitHub rather than these binaries being bundled with the normal distribution. Frankly, even if I wanted to have it be part of the normal distribution there would likely be some issue with regards to the [feature tags](https://github.com/godotengine/godot/pull/69538) that I added to Godot a while back, as they're not currently being "baked in" to Godot's export templates. This means that if I were to include both `.single` and `.double` libraries as part of the `[libraries]` section in the `.gdextension` file then anyone exporting builds containing Godot Jolt would need to explicitly add the `single` feature tag manually, which is going to cause a lot of confusion/frustration.

Considering that Godot itself also doesn't distribute `precision=double` builds I guess there's some precedence for needing to take extra steps anyway, so maybe just having a separate zip file on GitHub isn't the end of the world. But I'm still worried that I'll end up with people using a `precision=double` of Godot and then downloading it from the Godot Asset Library wondering why their editor crashes all of a sudden.

Actually verifying that some precision loss hasn't happened somewhere in the code is trickier though, but seeing as how I don't really have any functional tests to speak of anyway I guess that will end up being more of a "YOLO" situation, with some kind of test scene to be run manually as a smoke test before every release.

Anyway, give me a couple of days and I'll see if I can throw something together this weekend. Similar to the Android/iOS situation this change is long overdue. I have some Android-related problems that's gonna stall the release of 0.10.0-stable anyway, so I might even end up sneaking this into a new release candidate, depending on how things go.

**Comment by cridenour** [comment]
As a heavy precision=double user, we're already used to compiling our own GDExtensions so I wouldn't worry about distribution - just knowing it's compatible is great! 

In fact, I've found I need to export my own GDExtension header and JSON for GDExtension to play nice anyways so until Godot releases an official double build, an official GDExtension for it may not even work that broadly.

**Comment by SlashScreen** [comment]
I see. Since you know the engine far better than I, I'll leave you or a more qualified contributor to do that.

**Comment by mihe** [comment]
There it is.

Note that this is fairly untested still, so there may be some additional changes trickling in.

Anyway, here's a scene positioned at `[1000000, 1000000, 1000000]` with a single-precision build of Godot:

https://github.com/godot-jolt/godot-jolt/assets/4884246/f0fcadfe-37a7-49de-9caf-f8945daf4aee

... and here's that same scene at the same position with a double-precision build of Godot:

https://github.com/godot-jolt/godot-jolt/assets/4884246/3797291c-516f-40e1-b0ec-caa25727f89b

**Comment by mihe** [comment]
Before anyone else jumps on this, it seems there are some precision issues with `move_and_slide`, and thus presumably also `move_and_collide`/`test_body_motion`. I'm having trouble spotting the exact issue with it, so I'll reopen this until it's sorted out.

**Comment by cridenour** [comment]
The latest PR works great. Some notes:

I actually didn't need to use a custom extension_api.json or gdextension_interface.h. It seems this got better in 4.2, but just running the cmake build script created a working DLL. Which means you could distribute this (in contrast to my previous comment).

I'm curious of the `physics/jolt_3d/limits/max_linear_velocity` - is that something that could/should be different with double precision or not really related?

Thanks so much for this awesome project and your continued work.

**Comment by mihe** [comment]
> I actually didn't need to use a custom extension_api.json or gdextension_interface.h. It seems this got better in 4.2, but just running the cmake build script created a working DLL. Which means you could distribute this (in contrast to my previous comment).

Yeah, I've prepared the packaging CI to spit out a separate double-precision zip already, so it'll be available here on GitHub. It's looking likely that this extension will be merged into Godot as an official engine module in a not too distant future though, so the whole question of distribution won't be relevant for long either way.

> I'm curious of the `physics/jolt_3d/limits/max_linear_velocity` - is that something that could/should be different with double precision or not really related?

I'm honestly not sure if it would even make sense to crank that up. You're free to set it to a value higher than the soft limit I set in the project settings though. From what I understand its only real purpose is to prevent a chain reaction if something in the simulation goes haywire.

It's probably worth noting though that Jolt is only double-precision in the coordinate sense, and everything else (like velocities and displacements in general) are still single-precision, so I would imagine having a spaceship moving at crazy speeds probably won't work very well. Don't quote me on that though.

**Comment by cridenour** [comment]
Ha I'll hold off on implementing ludicrous speed but will push it up to match gameplay. Thanks!

**Comment by mihe** [comment]
Apparently there's something funky going on with soft bodies in double-precision builds, where the actual mesh completely explodes right away.

The simulation itself seems fine though, and the same problem seems to happen with Godot Physics, so I don't think there's anything on my end that's wrong.

I'll look into it tomorrow, just in case.

**Comment by fire** [comment]
I suspect the Vector/mesh format is not downcasted to float32 from float64.

**Comment by mihe** [comment]
Right, so soft bodies being broken was not something on the extension side of things, but was instead as @fire suspected, and something which turned out to be my fault in fact, so I've submitted a PR to fix it: godotengine/godot#88402

I also found another issue, which was that `cast_motion` (and thus `ShapeCast3D`) was broken in double-precision builds due to the safe/unsafe fractions in the extension API being bound with `real_t*`, which ends up emitted as `float*` in the API JSON file but then passed in as `double*` in double-precision builds. I've hacked around it for now (#782), but there probably needs to be a proper fix for this on the Godot side of things.

Anyway, with that I'll go ahead and close this again. It's all still somewhat untested, so for anyone taking this for a spin please be on the lookout for precision issues.

**Comment by mihe** [comment]
There's now also a prebuilt double-precision build, which can be found in the latest pre-release, 0.13.0-beta1, which you'll find [here](https://github.com/godot-jolt/godot-jolt/releases).

Note that this version targets the just recently released [Godot 4.3-beta1](https://godotengine.org/article/dev-snapshot-godot-4-3-beta-1/), so won't work with Godot 4.2. Also note that this version is not available through the Godot Asset Library, so you'll need to download it through GitHub.

A proper release will be out some time around Godot 4.3-stable.

**Comment by SlashScreen** [comment]
right on!

**Comment by mihe** [comment]
I figured I'd give a minor update here, as [0.13.0-stable](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.13.0-stable) has just been released, so if you've been relying on 0.13.0-beta1 for this functionality until now I would highly recommend updating, as this most recent release includes some important bug fixes.
