### ISSUE TITLE
Allow more precise contact allowed penetration

### ISSUE THREAD

**Issue by mgiraud** [godot-jolt/godot-jolt#372]
Godot 4.02
Windows 10
Intel(R) Core(TM) i7-7700K CPU
Nvidia 2080 Super

I've been playing again with your extension and i've come across an issue with a sphere collider rolling on an edge.
So when rolling on an edge, an extra collision occurs and modifies the trajectory of the sphere. At lower speed the balls even get stuck on the edge

Reducing contact allowed penetration and contact speculative distance to 0 prevents the issue but will certainly leads to some other weird behviours in more complexe scenes.

Maybe fiddling with other parametersmight fix the issue, but anyway here is the MRP
[edge-godot-jolt.zip](https://github.com/godot-jolt/godot-jolt/files/11518391/edge-godot-jolt.zip)

**Comment by mihe** [comment]
Fair enough. I wasn't quite sure what "resolution" to give these values, but I can give it another decimal point I guess, or maybe I'll just remove the step size altogether.

In the meantime you can work around this by just typing in the value into your `project.godot` file instead. The UI will still display the quantized value, but the actual value used will be whatever you've set it to.

With that said, I believe Jolt's "official" recommendation ([as mentioned here](https://github.com/jrouwe/JoltPhysics/issues/363#issuecomment-1384469118)) is to instead try to combine these into a single shape when possible, to avoid these types of "ghost collisions".
