### ISSUE TITLE
6DOFJoint cannot apply torque impulse when angular motor enabled

### ISSUE THREAD

**Issue by mgiraud** [godot-jolt/godot-jolt#380]
Godot 4.03
Windows 10
Intel(R) Core(TM) i7-7700K CPU
Nvidia 2080 Super

When the angular motor is enabled, applying a torque impulse does not have any effect. I don't know if this is intended but this is different from Godot Physics behaviour.

Another thing, the angular motor rotates in the opposite direction when switching the physics engine

As always, here is an MRP
* Press space to apply the impulse on one direction and release it to apply it the other way
* Switch the physics engine
[6dof-godot-jolt.zip](https://github.com/godot-jolt/godot-jolt/files/11531715/6dof-godot-jolt.zip)

**Comment by mihe** [comment]
Apologies for taking so long to get to this. It's been a hectic couple of days.

> I guess Godot Physics is ignoring the force limit.

It does seem that way. Setting the force limit to 0 with Jolt completely stops the motor, whereas it seems to keep going with Godot Physics. When looking at their code it seems like that particular property is implemented, so maybe it's a bug on their end.

Thanks for taking a second look. I'll go ahead and close this issue and make a new one for the motor direction.
