### ISSUE TITLE
Contact velocities lag behind by one tick

### ISSUE THREAD

**Issue by MightyPrinny** [godot-jolt/godot-jolt#388]
Hi, I've been sketching out a platformer controller with this physics engine, I've tried similar things with Godot's built in physics engine and bullet in Godot 3 and so far I think this is much better than bullet overall, 4.0's physics are not usable for this I think. 

First I was trying to replicate something I had tried in bullet and I noticed the moving platform was delayed by a frame, this works by applying a translation to the body's direct's state in _integrate_forces(), the velocity is obtained by searching the floor using contact monitoring and CI, this might not be the intended way to use the engine, but it's the best thing I could figure out so far. 

https://github.com/godot-jolt/godot-jolt/assets/18746022/afd1579c-8a91-41f0-ba14-d1240f58a181

Then I tried a rotating platform that tries to do the same thing, but fails with the cylinder shape, it works better with a capsule shape, probably because the collider's contact is near the bottom center of the shape, but I'm not sure how to get it working properly without hardcoding the logic, I'm not experienced with 3d physics enigines so I'm not sure if this is a real problem and I didn't try that in bullet so I don't have a point of reference.

The second set of moving platforms fix this in code, the linear platform fixes the 1 frame delay by calculating the velocity in _physics_process and character controller uses that value instead,  this didn't happen with bullet in Godot 3.5. The rotating one calculate's the player's velocity using the using the bottom center of the player as reference instead of the velocity for the contact point reported by the engine.

Here's the project:
[MJ.zip](https://github.com/godot-jolt/godot-jolt/files/11540134/MJ.zip)

**Comment by mgiraud** [comment]
@MightyPrinny I've maxed out the recovery amount to 100% on your MRP and the problem seems to be gone. Can you confirm ?

**Comment by mihe** [comment]
Actually, scratch that part about the estimation. I realized I mixed up contact velocities with contact impulses, which are the ones that are estimated. My bad.

**Comment by MightyPrinny** [comment]
Sorry, here's a more minimal reproduction project
[MINREPRO.zip](https://github.com/godot-jolt/godot-jolt/files/11549336/MINREPRO.zip)

https://github.com/godot-jolt/godot-jolt/assets/18746022/132123a9-7909-42ad-9487-85b3bd9d6a8f

**Comment by mihe** [comment]
I was close to pushing a fix for this, before I realized that this is actually the way it's meant to be. The velocity returned from `get_contact_collider_velocity_at_position` is the velocity at the time of contact/impact and not the collider's current velocity.

If you want the platform's current velocity at the contact point you'll likely have to calculate it yourself using something like this:

```gdscript
collider.linear_velocity + collider.angular_velocity.cross(point_relative_to_center_of_mass)
```

You can unfortunately only get a body's center-of-mass from its `PhysicsDirectBodyState3D` though, which might make things a bit trickier, but you can always set a custom center-of-mass to `(0, 0, 0)` which would allow you to use `global_position` as the center-of-mass.

**Comment by MightyPrinny** [comment]
@mihe thank you for looking into it, I'll try your suggestion however the linear velocity is already off by 1 physics step and I'd already tried using the collider's linear velocity instead of the contact velocity, I only got it to look right when I precomputed the linear velocity of the moving platform in _physics_process and then use that to move the other body, but it would break if the moving platform encounters an obstacle .

**Comment by mihe** [comment]
Note that the processing order of the nodes matters as well, which is dictated by the order they're specified in the scene tree. So having the ones producing the linear velocity above the ones reading it should make a difference.

**Comment by mihe** [comment]
You can also control it using the "Process Priority" property, where a lower value is processed first.
