### ISSUE TITLE
Areas don't detect bodies frozen with static freeze mode

### ISSUE THREAD

**Issue by mgiraud** [godot-jolt/godot-jolt#397]
Godot 4.0.3
Godot-Jolt 0.1.0-stable

I'm not sure the title is accurate, here is what happens. 
When freezing a rigidbody colliding with an area3D, the `body_entered` signal is triggered each time the body is unfrozen.
The behaviour between the two engines is different

With Jolt Physics :

https://github.com/godot-jolt/godot-jolt/assets/11818237/36c078ec-c704-465c-807b-a0b88ed67f5d

With Godot Physics :

https://github.com/godot-jolt/godot-jolt/assets/11818237/b25f3e8d-d61f-4b67-ab10-7830748d491b

MRP : 
[freeze-area-godot-jolt.zip](https://github.com/godot-jolt/godot-jolt/files/11566807/freeze-area-godot-jolt.zip)

**Comment by mihe** [comment]
I should probably clarify in the README that this applies to freezing as well, actually.

Thank you for reporting it.

**Comment by mihe** [comment]
I'm reopening this. We had some discussion in #391 and seem to have found a path forward for supporting this. I figured it's not immediately obvious that static freezing is the same as a static body, so having two separate issues seems justified.
