### ISSUE TITLE
Collision layers/masks differ in behavior from Godot Physics

### ISSUE THREAD

**Issue by jrouwe** [godot-jolt/godot-jolt#400]
Hello,

Creating this issue to discuss the differences between Godot collision_layer / masks and those provided by Godot Jolt because of discussion in https://github.com/jrouwe/JoltPhysics/discussions/544.

I've looking through the documentation a bit and I'm wondering what exactly would be needed from Jolt in order to support this. As far as I understand Godot Jolt does:

colliding = (layerA & maskB) OR (layerB & maskA)

When rigid bodies collide they interact normally.

whereas Godot does:

colliding = layerA & maskB

for normal collision queries and when rigid bodies collide we have:

| layerA & maskB  | layerB & maskA | Result |
| ------------- | ------------- | ------------- |
| False | False | Objects don't collide |
| True | True | Objects collide and interact normally |
| True | False | Objects collide and object B is treated as having infinite mass |
| False | True | Objects collide and object A is treated as having infinite mass |

My guess is that if both bodies end up having infinite mass (because the other was already kinematic) that the collision is discarded as well.

Does this summarize things correctly?

As far as I can see there is no issue for collision queries. ```ObjectLayerFilter::ShouldCollide``` can be implemented to do the same thing as Godot 4 does as you can store the layer of object A in the ObjectLayerFilter and just and it with the layer that is being passed in. Is this correct? (I'm hoping this is already the case now)

I think the only problem is for the interaction between rigid bodies. Jolt uses ```ObjectLayerPairFilter::ShouldCollide``` to determine if two objects should collide and there you are forced to return (layerA & maskB) OR (layerB & maskA) because this function only determines if they collide not how. It sounds like the only thing you actually need is the ability to override the masses of the colliding bodies? I haven't fully investigated this but it looks like it would be possible to either override the motion types for the bodies in ContactSettings (you would only be able to go in the direction Dynamic -> Kinematic -> Static and not e.g. promote a Static object to Dynamic). Alternatively there could be an 'inverse mass scale' for body 1 & 2, setting it to 0 would make the body have infinite mass, setting it to 1/2 would make it twice as heavy etc. Inverse inertias would scale accordingly.

What do you think about this?

**Comment by mihe** [comment]
> Does this summarize things correctly?

Yes, that seems to be an accurate summary of it.

Just to double-check myself I made a test scene that you can find here: [layers_and_masks.zip](https://github.com/godot-jolt/godot-jolt/files/11576798/layers_and_masks.zip)

This is what it looks like with the (pre-configured) Godot Physics:

https://github.com/godot-jolt/godot-jolt/assets/4884246/7c7ac640-a92a-42dd-9ea2-da4550d5d12b

This is what it looks like when changing the physics engine to Jolt:

https://github.com/godot-jolt/godot-jolt/assets/4884246/850ac9cb-2f62-466d-8362-ca6a0ba6b6b5

(Apparently Godot Physics doesn't apply linear velocities on kinematic/frozen bodies, which took me by surprise. I'll have to investigate that discrepancy. Just look past that part I guess.)

> As far as I can see there is no issue for collision queries. ObjectLayerFilter::ShouldCollide can be implemented to do the same thing as Godot 4 does as you can store the layer of object A in the ObjectLayerFilter and just and it with the layer that is being passed in. Is this correct? (I'm hoping this is already the case now)

Yes, that is [indeed](https://github.com/godot-jolt/godot-jolt/blob/a33143d3c3261ffbb59fd39af69164544676c698/src/spaces/jolt_query_filter_3d.cpp#L50) how it works already.

> you are forced to return (layerA & maskB) OR (layerB & maskA) because this function only determines if they collide not how

I'm glad to hear you say that. That lines up with my understanding of it. I was worried I might've missed something.

> Alternatively there could be an 'inverse mass scale' for body 1 & 2, setting it to 0 would make the body have infinite mass, setting it to 1/2 would make it twice as heavy etc. Inverse inertias would scale accordingly.

Are you saying this too would be something you would override through `ContactSettings`?

> What do you think about this?

I think either of your two solutions sound great. If I had to pick one then I'd say the inverse mass scale sounds pretty good.

However, doing it through `ContactListener` would mean me having to [do lookup](https://github.com/godot-jolt/godot-jolt/blob/a33143d3c3261ffbb59fd39af69164544676c698/src/spaces/jolt_layer_mapper.cpp#L130-L133) using Jolt's object layer, for every single contact ever, to get the collision layer/mask that it maps to, which might not be ideal from a performance perspective. There's probably a separate discussion to be had about better ways to deal with storing the layers/masks (which are two 32-bit integers), but that's the reality as of right now, so I figured I should mention it.

**Comment by jrouwe** [comment]
> Are you saying this too would be something you would override through ContactSettings?

Yes, correct.

> However, doing it through ContactListener would mean me having to [do lookup](https://github.com/godot-jolt/godot-jolt/blob/a33143d3c3261ffbb59fd39af69164544676c698/src/spaces/jolt_layer_mapper.cpp#L130-L133) using Jolt's object layer

That's correct too, but I'm not sure what the alternative is. Godot has just hardcoded this behavior, that makes things easy. But I have to cater to different people, so I need to ask the client code what they want to do. The only place where I can do that is in the ContactListener.

**Comment by mihe** [comment]
Totally understandable! Just as long as we're both aware of it. :)

I've been meaning to do some profiling to see how bad that current `unordered_map` + `shared_mutex` lookup is. It was a very quick-and-dirty implementation that just ended up staying there. I'm sure there's more clever ways of going about it. Seeing as how the key is a globally incremented ID, and with the map being fairly small, then switching to some type of flat/vector map seems like one easy upgrade at least.

**Comment by jrouwe** [comment]
The functionality was added in jrouwe/JoltPhysics#580
