### ISSUE TITLE
Scaling bodies attached to joints results in the bodies translating

### ISSUE THREAD

**Issue by phelioz** [godot-jolt/godot-jolt#427]
Hey!

Have some problems with RigidBody3D instances that I attach to a scaled PhysicsBody3D (StaticBody3D/RigidBody3D) with Generic6DOFJoint3D.

I had no problem in v0.2.0-rc1 with attaching the RigidBody3D to a scaled PhysicsBody3D but in the 0.2.0-stable artifact I encounter problems. 
The RigidBody3D I want to attach to the scaled PhysicsBody3D gets moved in the physics step after attaching it.
The offset it moves seems to correlate to the scale the other PhysicsBody3D is altered by.

So it seems the scale of the other PhysicsBody3D is not accounted for in some way when attaching the joint.

**Comment by mihe** [comment]
Almost definitely related to #424, which I thought I could sneak in without creating a new release candidate, which was not a wise choice.

The worst part is that I tested scaling bodies connected to a joint, but couldn't quite remember exactly how this was meant to look/behave/work. I threw together a quick test with a scaled body on a `SliderJoint3D` (which shares the relevant code) and thought that it looked okay, but I guess I should've tested it more rigorously.

Any chance you could provide a repro project that mimics your setup?

**Comment by phelioz** [comment]
Nice :) Here are two minimal projects that display the difference in behaviour between 0.2.0-rc1 and 0.2.0-stable
[jolt-physics-joint-0.2.0-stable.zip](https://github.com/godot-jolt/godot-jolt/files/11665062/jolt-physics-joint-0.2.0-stable.zip)
[jolt-physics-joint-0.2.0-rc1.zip](https://github.com/godot-jolt/godot-jolt/files/11665063/jolt-physics-joint-0.2.0-rc1.zip)

**Comment by mihe** [comment]
Awesome, thank you. That seems to work with the pending PR.

In the interest of getting as many people as possible to test the new joint behavior introduced in #424, I'll go ahead and cut a 0.2.1 release right away.

That was sloppy of me. I'm very glad you caught it so quickly.

**Comment by mihe** [comment]
[0.2.1-stable](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.2.1-stable) is now live.
