### ISSUE TITLE
"Snapping" Issue When Moving a Rigidbody-Based Player

### ISSUE THREAD

**Issue by jamesdimick** [godot-jolt/godot-jolt#443]
I'm posting this issue as requested by @mihe . It relates to this discussion: #442 

Basically, I'm using some simple logic to move a rigidbody "character" with physics, rather than using stuff like built-in character controllers. It is a third-person camera setup.

I have used this same setup in the built-in physics in Godot 4 and not had this issue. I also didn't have this issue when using the same code in Bullet Physics in Godot 3.

The issue doesn't seem very apparent when constantly holding down inputs to make the character move, but shows up when you let go of the controls and the player comes to a stop. There is this kinda weird movement that happens on it's own. It sorta looks like the character is "snapping" to a certain position. It is a bit hard to describe, but I have created a Minimal Reproducible Example that reproduces the issue, at least from my tests.

The character physics are a bit loose/floaty in the repro project, but that is simply a symptom of me removing all non-essential code to get it down to an MRE, so don't pay attention to that part.

The MRE can be found [here](https://github.com/jamesdimick/godot-jolt-issue-repro).

**Comment by mihe** [comment]
> but shows up when you let go of the controls and the player comes to a stop

I must admit I can't really see anything out of the ordinary when I let go of the controls on my end.

> sorta looks like the character is "snapping" to a certain position

I can however see something like what you're describing when bumping into some of the lower obstacles:

https://github.com/godot-jolt/godot-jolt/assets/4884246/0df5355c-c503-48c6-8d15-5554ee5df21c

If this is similar to the effect you're seeing then it can be explained by me implementing axis-locking using Jolt's 6DOF constraint. So what you're seeing is the expected collision happening and Jolt trying to solve for that constraint.

I've run into this as well and I noted it under the list of differences as "a body can technically deviate a bit from its locked axes", but obviously this doesn't provide any comfort when the issue shows up for something as core as a character controller.

This problem seem to be alleviated in part by enabling CCD, which you seem to have already done, and which I disabled in the video to more reliably reproduce the issue.

I believe the more effective way of dealing with this is by bumping up the position iterations for the constraint. Unfortunately, even though Jolt supports overriding the number of velocity/position iterations per constraint instance, I don't provide any such facility right now. You can set it globally though, under the "Jolt 3D" project settings page, but I believe this applies to all types constraints, including contact constraints, which presumably gets expensive at scale.

Here's what it looks like if you give the global position iterations a very liberal value of 64 iterations:

https://github.com/godot-jolt/godot-jolt/assets/4884246/74e7ddcd-eec5-4495-8ad5-b2c6d6ea841f

What would be your recommendation in cases like this, @jrouwe, where you use a 6DOF constraint to lock the rotation of a dynamic body? I've seen you apply similarly liberal values to some of the constraints in your tests. Should I just hardcode the override of position (and velocity?) iterations for this particular constraint to something like 64, and consider that appropriate for all/most cases, or do you see value in exposing project settings for controlling the iterations of this particular constraint?

... or maybe there's something else entirely going on that I'm missing? :)

**Comment by mihe** [comment]
(I embedded your video into your comment. I couldn't view the hot-linked file for some reason.)

I see what you mean now. That does seem to be a separate issue from what I stumbled upon.

If I turn on Jolt's debug rendering and draw the velocities the issue becomes a lot more apparent:

https://github.com/godot-jolt/godot-jolt/assets/4884246/edcb53cb-b9fb-4a30-95b8-d1077391384a

It almost looks as if the friction becomes anisotropic and doesn't get applied evenly in all world axes.

I'm not sure there's much on my end that could affect this. I'll have to see if I can reproduce this in Jolt's `Samples` application.

**Comment by mihe** [comment]
@jrouwe I've confirmed that this is indeed reproducible in `Samples`.

Here's some code you can plug into the `Initialize()` method of a `Samples` test:

```cpp
Body &floor = *mBodyInterface->CreateBody(BodyCreationSettings(new BoxShape(Vec3(200.0f, 1.0f, 200.0f), 0.0f), RVec3::sZero(), Quat::sIdentity(), EMotionType::Static, Layers::NON_MOVING));
floor.SetFriction(1.0f);
mBodyInterface->AddBody(floor.GetID(), EActivation::DontActivate);

Body& capsule = *mBodyInterface->CreateBody(BodyCreationSettings(new CapsuleShape(0.5f, 0.5f), Vec3(0, 2.5f, 0), Quat::sIdentity(), EMotionType::Dynamic, Layers::MOVING));
capsule.SetFriction(1.0f);
capsule.SetLinearVelocity(Quat::sRotation(Vec3::sAxisY(), DegreesToRadians(10.0f)).RotateAxisZ() * 50.0f);

SixDOFConstraintSettings constraint_settings;
constraint_settings.mPosition1 = mBodyInterface->GetCenterOfMassPosition(capsule.GetID());
constraint_settings.mPosition2 = constraint_settings.mPosition1;
constraint_settings.MakeFixedAxis(SixDOFConstraintSettings::EAxis::RotationX);
constraint_settings.MakeFixedAxis(SixDOFConstraintSettings::EAxis::RotationY);
constraint_settings.MakeFixedAxis(SixDOFConstraintSettings::EAxis::RotationZ);

TwoBodyConstraint* constraint = constraint_settings.Create(Body::sFixedToWorld, capsule);

mBodyInterface->AddBody(capsule.GetID(), EActivation::Activate);
mPhysicsSystem->AddConstraint(constraint);
```

**Comment by jrouwe** [comment]
Thanks for reporting, I will investigate (and I created a ticket in Jolt for it, see above).

**Comment by jrouwe** [comment]
B.t.w. to prevent a body from rotating you can also use the trick by setting the inverse inertia to (0, 0, 0) as demonstrated in TwoDFunnelTest. This should get rid of the leaning over on bounce.

**Comment by mihe** [comment]
> and I created a ticket in Jolt for it

Thank you. I should probably have done that. I'll keep that in mind for next time.

> you can also use the trick by setting the inverse inertia to (0, 0, 0)

Oooh. I did not know about this! I'll have to experiment with that.

**Comment by jrouwe** [comment]
FYI: I found the issue and fixed it. See https://github.com/jrouwe/JoltPhysics/issues/569

**Comment by mihe** [comment]
Fantastic, thank you!

I can confirm that the fix worked like a charm.

The inertia trick for preventing the body from rotating also worked like a charm. It turned out that Godot Physics was using the same exact trick for its implementation of the `lock_rotation` property.

Both of these will be included in the next release, which will likely be out some time friday.
