### ISSUE TITLE
Godot 4.1 Support

### ISSUE THREAD

**Issue by JamDoggie** [godot-jolt/godot-jolt#486]
As far as I can tell, Godot 4.1 introduced some breaking changes that require extensions to update. This is currently what happens when trying to install the Jolt extension on Godot 4.1:

![image](https://github.com/godot-jolt/godot-jolt/assets/17690526/ab0bb623-8b7e-486a-82d9-36ba8e5a10dd)

**Comment by mihe** [comment]
The release candidate [0.4.0-rc1](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.4.0-rc1) supports Godot 4.1 already.

The proper stable release should hopefully be up here on GitHub some time later today. It won't show up on Godot Asset Library until it gets approved though.

**Comment by mihe** [comment]
[0.4.0-stable](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.4.0-stable) has now been released.
