### ISSUE TITLE
`move_and_slide` doesn't respect surface velocities

### ISSUE THREAD

**Issue by mihe** [godot-jolt/godot-jolt#491]
I believe this is a more general problem with all kinematic bodies and not necessarily related to `move_and_slide`, but it seems it doesn't currently react to surface velocities, like the `constant_linear_velocity` property of `StaticBody3D`.

Here's how to reproduce it:

1. Download this project: [character_surface_velocities.zip](https://github.com/godot-jolt/godot-jolt/files/11999504/character_surface_velocities.zip)
2. Run the main scene
3. Note how the character falls onto the floor and then proceeds to slide off it
4. Switch physics engine to Jolt
5. Run the main scene again
6. Note how the character only falls onto the floor but doesn't proceed to slide off it

**Comment by jbromberg** [comment]
Was this due to a lack of support in Jolt? If so, it's been released in Jolt 4.0 https://github.com/jrouwe/JoltPhysics/releases/tag/v4.0.0

**Comment by mihe** [comment]
No, surface velocities are already supported by this extension, and were in fact very generously added (or at least expedited) into Jolt in response to them not being supported in this extension at first, as part of #331. That goes for a lot of the features and fixes listed in those release notes.

I've been tracking Jolt's master branch since the start of this project, so its version numbers don't really mean a whole lot as far as this extension is concerned.

The problem with this issue is with regards to how surface velocities affect the movement of kinematic bodies, as opposed to the movement of rigid bodies, which is something that needs to be accommodated for on my side of things.

**Comment by mikest** [comment]
I am also running into this problem. I have a Character3D which is interacting with a Kinematic StaticBody3D. When I set the `constant_linear_velocity` and `constant_angular_velocity` my character can ride on the moving platform, but when I switch to Jolt they stay fixed in global space and fall off.

I see this issue has been reported in #331 , #92.

Is it supportable? I know that #331 references a different technique.

**Comment by mihe** [comment]
This was fixed in #696, which hasn't been released yet.

I'm aiming to have a new release published within the next day or two.

**Comment by mihe** [comment]
@mikest Reading your comment a bit closer, I only just now realized what you were trying to do.

You should ideally switch your platform to be an `AnimatableBody3D` instead, which (despite inheriting from `StaticBody3D`) is a proper kinematic body. That way you don't have to rely on things like `constant_*_velocity` for `move_and_slide` to pick up on the proper velocity of the platform. You can just translate/rotate it as normal and `move_and_slide` should ride along accordingly.

`StaticBody3D` is not a kinematic body, but a static body, and you will likely see jank or other weird issues if you try to move one around, especially if it ever interacts with something like `RigidBody3D`.
