### ISSUE TITLE
Support for `SoftBody3D`

### ISSUE THREAD

**Issue by jrouwe** [godot-jolt/godot-jolt#503]
I've been working on soft body support and I'm trying to prioritize features that will be used by godot. I'm creating this ticket to let you know of my progress, the kind of things I'm running into and to have a place to discuss the feature.

First of all I have a difficult time to narrow down what it exactly is that godot supports. I've created a test scene:

[SoftBody.zip](https://github.com/godot-jolt/godot-jolt/files/12136548/SoftBody.zip)

As far as I can see there no collision detection implemented between soft bodies, but it is also quite possible that I don't understand the layer/mask pairs and that it is possible to get the 2 to collide. Am I doing something wrong?

https://github.com/godot-jolt/godot-jolt/assets/1621693/7c542660-ce57-453d-b1da-849fa47e62c9

B.t.w. I'm pinning one of the vertices of each shape, because if I don't this is what I get:

https://github.com/godot-jolt/godot-jolt/assets/1621693/e5a10bcb-11a7-49ee-9548-ea2e5c6f2c8f

The rigid body sphere collides with the soft bodies, but while playing around with this I found the collision response very unreliable. Often the sphere passes through the soft body without being affected by it. I also had to export my own sphere from blender because the default sphere mesh (or any other default godot mesh) has a seam so will deflate immediately. This is a movie of when it works:

https://github.com/godot-jolt/godot-jolt/assets/1621693/5ebd6509-f7cb-4d71-9a4f-01fb6aad9ed0

Finally while implementing 'pressure' I ran into what I think is a bug in godot. The force on the vertices of the soft body is calculated by ```force = pressure_constant * area / volume``` but I think the area calculation is incorrect:

https://github.com/godotengine/godot/blob/6588a4a29af1621086feac0117d5d4d37af957fd/servers/physics_3d/godot_soft_body_3d.cpp#L255-L261

In this loop it distributes the area of the faces of the soft body to the vertices, which will later be used to distribute the pressure force. Consider this simple octahedron:

![image](https://github.com/godot-jolt/godot-jolt/assets/1621693/b6564efe-a7b5-4a6e-80e1-a28d1d9200f6)

The loop will add the area A to the vertex v 4 times and then divide by 4 again in the next code block. The same will happen for all other vertices in the shape, this means that the total area is 6 * A while it in fact should be 8 * A.

I'm obviously not going to copy this behavior, which means that the pressure coefficient is going to behave different in Jolt than it will in godot (and it will depend on the topology of the shape how different it is).

**Comment by mihe** [comment]
I must admit I have very little experience with `SoftBody3D` in Godot. I've only ever seen examples of them being used as cloth in Godot, like a cape or a curtain, and never actually as soft-body against soft-body.

> The rigid body sphere collides with the soft bodies, but while playing around with this I found the collision response very unreliable.

My impression is that `SoftBody3D` is in a similar situation as with the joints, where stuff was brought over from Bullet and left in some intermediate/broken state. Even the [documentation](https://docs.godotengine.org/en/stable/classes/class_softbody3d.html) for `SoftBody3D` admits to it being very buggy.

> As far as I can see there no collision detection implemented between soft bodies, but it is also quite possible that I don't understand the layer/mask pairs and that it is possible to get the 2 to collide. Am I doing something wrong?

I figured this ignoring of collisions was just a symptom of the implementation being broken, so I pulled in your setup into Godot 3 and I'm seeing much the same behavior there with regards to soft-bodies ignoring eachother. This is very odd since I know for a fact that Bullet supports this just fine. In fact, I'm looking at two Stanford bunnies bouncing off eachother in Bullet's example browser as we speak.

Here's the Godot 3 project if you want to try it for yourself:

[SoftBody_Godot3.zip](https://github.com/godot-jolt/godot-jolt/files/12136747/SoftBody_Godot3.zip)

You'll notice there that pressure and rigid-body interactions works just fine. So I think using that as your reference is probably your best bet, much like the situation with the joints. As long as the interface lines up well enough that there's some clear connection between the parameters in either interface then it's all good. The behavior itself is clearly nothing that should be replicated, as you say.

Anyway, I'll do some more digging as to why the soft-bodies are ignoring eachother like that. That's very strange.

**Comment by mihe** [comment]
Well, I found a 4 year old issue (godotengine/godot#27039) that seems to confirm that collisions between soft-bodies is explicitly not supported in Godot 3. I don't really understand why though. Perhaps support for this in Bullet was added at some later point and never incorporated into Godot 3.

As for Godot 4, this seems to also be explicitly not supported, as seen [here](https://github.com/godotengine/godot/blob/6588a4a29af1621086feac0117d5d4d37af957fd/servers/physics_3d/godot_space_3d.cpp#L1064).

**Comment by jrouwe** [comment]
Thanks for checking! It makes things a whole lot easier! So then I won't support soft body vs soft body for the first iteration either, which is good news as then I have all the ingredients ready so the next step will be to define an API.

**Comment by jrouwe** [comment]
I just merged a first soft body implementation in Jolt in https://github.com/jrouwe/JoltPhysics/commit/5c9f7a60436f919d7e3409aeeb49861c679500f7.

I think with this it should be possible to implement everything that ```SoftBody3D``` exposes.

Let me know if you need any help.

**Comment by mihe** [comment]
Awesome! It might be a while before I get to this, but I'll let you know if/when I need any help.

**Comment by PiCode9560** [comment]
Just want to know, when is the estimate time for this to be available?

**Comment by jrouwe** [comment]
Let me know what you think of the API!

**Comment by mihe** [comment]
Well, I managed to hit a pretty unfortunate blocker, which is that the interface through which one pushes the updated particle positions to the rendering isn't actually bound to GDExtension properly, so there's no way for me to make anything move visually.

I'll see about making a pull request to fix this, but there's a chance that this won't be cherrypicked into Godot 4.1, meaning support for `SoftBody3D` will have to wait until Godot 4.2, which I believe won't be released until some time late October or early November.

I'll keep you posted.

**Comment by jrouwe** [comment]
That's quite unfortunate! I expected lots of issues in Jolt but didn't expect that the bindings would be missing in Godot.

**Comment by jrouwe** [comment]
Nice! 

P.S. I wonder how much of a performance bottleneck those 2 virtual calls per vertex are going to be, it would have been nicer if godot had designed a batch set interface instead of the current per vertex one.

**Comment by mihe** [comment]
Yeah, I've been thinking about that as well. The problem is potentially much worse than just vtable indirection when you factor in the marshalling code generated by godot-cpp as well. I figured if it ends up being a bottleneck I can see about making a pull request for some alternative interface.

**Comment by jrouwe** [comment]
I was looking at the PR in godot and noticed it hadn't been integrated yet (even though the 4.2 integration has started), it looks like all that's needed is to add a line to the documentation?

**Comment by mihe** [comment]
I was waiting for some kind of final decision on whether a breakage was acceptable or not. I must admit I struggle to understand who has authority over these kinds of things, but seeing as how the winds seem to be blowing towards a breakage being acceptable I guess I'll go ahead and push that along with the requested documentation.

**Comment by jrouwe** [comment]
Yay, the PR got accepted! Now the long wait for 8.2 starts!

**Comment by ChildLearningClub** [comment]
Hi, On 4.2.rc1 should SoftBody3D be working with Godot Jolt?

**Comment by ChildLearningClub** [comment]
@mihe thank you for responding and to both you and @jrouwe for your work on Jolt! ⚡️

**Comment by PhilNikitin** [comment]
@mihe thank you for your work! Does it work on 4.3 dev?

**Comment by jrouwe** [comment]
@mihe Is there anything that I can do to help out with this one? I'd love to see it implemented as it seems like one of the last big missing features.

**Comment by mihe** [comment]
As far as I'm aware the only showstopper is me actually sitting down and doing it.

But yes, I know this is long overdue. There's some pervasive refactoring involved with this, since the current class hierarchy assumes that all physics objects are rigid bodies, which along with some other behind-the-scenes stuff has made me push this (and other bigger tasks) in front of me for a while now.

Starting next week I should have more time available to work on stuff like this, so just hold out for a little bit longer.

**Comment by mihe** [comment]
Plenty of work left to do, but I've at least got something that's moving some vertices around, finally:

https://github.com/godot-jolt/godot-jolt/assets/4884246/7ebb631d-3b54-41c3-b586-bf06cbc015c7

@jrouwe I'm not entirely sure what the correct set of edge constraints are supposed to be. Right now I'm just adding one constraint for each edge of the faces, so triangle A-B-C would have constraints A-B, B-C and C-A, which obviously seems to be working well enough in this particular case, but should I also be adding opposite constraints as well, meaning B-A, C-B and A-C?

**Comment by jrouwe** [comment]
Looking good!

> should I also be adding opposite constraints as well, meaning B-A, C-B and A-C

No you shouldn't add those. Also if you have triangle ABC and ABD then AB should only be added once.

Note that it is not forbidden to add the same edge twice. This will result in the solver running the edge multiple times, so it will be harder to violate. If you would add all edges 2x then that would be similar to doubling ```SoftBodyCreationSettings::mNumIterations```. It's not completely the same since ```Optimize()``` can reorder edges to group them for parallel execution.

**Comment by mihe** [comment]
That took a little longer than it probably should have, and I'm sure there's a bug or two left to squash, but there it is.

https://github.com/godot-jolt/godot-jolt/assets/4884246/7baf9430-ab90-47e5-bea8-0c713c6cb6c9

It might be a little while before I cut a new release though. I'd like to try to get some other things in before that.

@jrouwe The two things still missing from the Jolt side of things are contact listener support and potentially some kind of support for sensors.

I would presumably need contact listener support for implementing support for asymmetrical/one-way collisions (i.e. #400 but for soft bodies), which currently isn't working and thus differs from Godot Physics.

The sensor stuff in Godot Physics doesn't seem to be used for actually emitting enter/exit events to scripts or anything like that, but instead is used for per-area wind simulation properties, as seen [here](https://docs.godotengine.org/en/stable/classes/class_area3d.html) (code [here](https://github.com/godotengine/godot/blob/36e943b6b20cb7a8a89bc30489c4a81c3e149d74/servers/physics_3d/godot_soft_body_3d.cpp#L913-L953)). It's also used for per-area gravity overrides, similar to rigid bodies.

**Comment by jrouwe** [comment]
Nice! I'll take a look at contact listeners. What I had in mind is a single call that provides all contacts at once (to avoid 1000s of callbacks). And probably 1 call per touched body before the narrow phase similar to the validation call of the regular listener. Do you see any problems with that?

**Comment by mihe** [comment]
> Do you see any problems with that?

No, that sounds like it should work fine. I really just need to be able to set the inverse mass/inertia on every contact, as well as add the contact position to the list of debug contacts. Everything else is just gravy.

**Comment by mihe** [comment]
I realize it's been a long wait for those of you who have been waiting for a release with this, and it certainly got drawn out for longer than I had originally planned, but you can now find `SoftBody3D` support included in the latest pre-release, 0.13.0-beta1, which you'll find [here](https://github.com/godot-jolt/godot-jolt/releases).

Note that this version targets the recently released [Godot 4.3-beta1](https://godotengine.org/article/dev-snapshot-godot-4-3-beta-1/), so won't work with Godot 4.2. Also note that this version is not available through the Godot Asset Library, so you'll need to download it through GitHub.

A proper release will be out some time around Godot 4.3-stable.

**Comment by mihe** [comment]
I figured I'd give a minor update here, as [0.13.0-stable](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.13.0-stable) has just been released, so if you've been relying on 0.13.0-beta1 for this functionality until now I would highly recommend updating, as this most recent release includes some important bug fixes.

Note that the release on the Godot Asset Library is still pending approval as of typing this, so you might need to download it from the link above.
