### ISSUE TITLE
Add profiler timings

### ISSUE THREAD

**Issue by jrouwe** [godot-jolt/godot-jolt#507]
Follow up for https://github.com/godotengine/godot-proposals/issues/7308#issuecomment-1647762564 (trying not to pollute that main tracker).

Hooking up profiling should be very simple, just define ```JPH_EXTERNAL_PROFILE``` and then implement the constructor and destructor for this class:

https://github.com/jrouwe/JoltPhysics/blob/b1cd84951022a565a23f33ff77ffee9e71487bbc/Jolt/Core/Profiler.h#L27-L28

You can use mUserData to store context information if needed.

The constructor should start the measurement / the destructor should stop it. Note that the implementation needs to be thread safe as it is called from all worker threads and that it needs to be fast since it is called a LOT.

You can see the system in action by pressing 'T' in the samples app and opening ```profile_chart_1.html```. This shows you something like:

![image](https://github.com/godot-jolt/godot-jolt/assets/1621693/12761e1c-dfef-4c9a-a6c3-6e9c8d44f0a2)

where each bar would be a construction and destruction of ```ExternalProfileMeasurement``` (obviously the internal profiler is not using that class but you get the idea).

**Comment by mihe** [comment]
I don't really know how to proceed with this one. Something like the more traditional profiler that Jolt supports might perhaps be in some future plans for Godot, but I'm not aware of any such thing currently, so the two don't really seem compatible to me.

@jrouwe Is it possible (and does it even make sense) for Jolt to report timings for the various "broad strokes" within `PhysicsSystem::Update`, like some of the ones described under "The Simulation Step in Detail" [here](https://jrouwe.github.io/JoltPhysics/), similar to [the ones](https://github.com/godotengine/godot/blob/332bc469c46e1372cdf3222bd3d31c382afc2784/servers/physics_3d/godot_physics_server_3d.cpp#L1677-L1681) emitted by Godot Physics? I'm not sure how useful that would be to people in practice, other than seeing some cool numbers, but that seems to be about as far as I would be able to take this ticket.

**Comment by jrouwe** [comment]
You're wrapping the ```JobSystem``` right? You could perhaps just track the running time of each job. The jobs have a ```mJobName``` (no accessor for it currently, but that is easily made) that you could perhaps use? There is a limited set of job names but each type of job can run multiple times per update, so you would need to keep track of the totals. There is a little bit of work done outside of the jobs but this mostly boils down to building the jobs.

**Comment by mihe** [comment]
> You're wrapping the JobSystem right?

If by wrapping you mean implementing, then yes.

> You could perhaps just track the running time of each job. The jobs have a `mJobName` (no accessor for it currently, but that is easily made) that you could perhaps use? There is a limited set of job names but each type of job can run multiple times per update, so you would need to keep track of the totals.

That could work. I'll give that a try. Thank you.

Also, you do get the job name through the override of `JobSystem::CreateJob`, so an accessor shouldn't be necessary I think.

**Comment by mihe** [comment]
To anyone who decides to actually give this a try: I must admit that I don't really understand how this profiler works. Even when using Godot Physics the profiler (for some strange reason) decides to filter out most of the timings and only display at most one or maybe two of them, but often none at all. The numbers themselves look fine though, and I'm doing it the same way as Godot Physics, so I'm assuming the issue lies on the Godot side of things, assuming I'm not just using it wrong to begin with.
