### ISSUE TITLE
`intersect_ray`'s collider and RayCast3D's get_collider() always return <Object#null>

### ISSUE THREAD

**Issue by Lippanon** [godot-jolt/godot-jolt#534]
Godot version: v4.2.dev.custom_build [f7bc653cb] (I also tested with an earlier build, around a week old or so, unsure)
Godot Jolt: c129fb93f4c4f523a597d64e0ac53612b874b5cf and 976abb25f61c49573fb537984e7943eea63a1427
Windows 10, Vulkan

PhysicsDirectSpaceState3D's `intersect_ray`'s collider seems to always return <Object#null> (on a hit). 
RayCast3D node's get_collider() (when is_colliding() is true) also.
![image](https://github.com/godot-jolt/godot-jolt/assets/115422160/4a19fa99-30b0-474a-ac99-9c24d5354381)

This is a recent regression, it could be that something changed in Godot that isn't yet reflected in GJolt, apologies if so.

This MRP is the example project with a script attached to the main node that simply prints both of these to demonstrate the null every second: 
[examples.zip](https://github.com/godot-jolt/godot-jolt/files/12295665/examples.zip)

Perhaps not related but I noticed there is an error printed out after I added RayCast3D to the test, if you disable it (`enabled` property false), there's no error.

The bug doesn't occur with GodotPhysics. Please let me know of any workaround.

**Comment by mihe** [comment]
As mentioned in [`README.md`](https://github.com/godot-jolt/godot-jolt#what-versions-of-godot-are-supported) as well as the release notes, this extension only officially supports the latest stable version of Godot.

With that said, it seems this is related to godotengine/godot#71233, which has changed the binary layout of the ray-cast results and thereby (seemingly on accident) introduced a breaking change to GDExtension.

The only workaround is to fall back to a commit before godotengine/godot@a56e960150718374533d0a8378fb10db2219ddef, but anything beyond 4.1.1-stable puts you at risk of running into these types of breakages.
