### ISSUE TITLE
`cast_motion` not detecting a specific wall

### ISSUE THREAD

**Issue by Gamepro5** [godot-jolt/godot-jolt#569]
[bug.zip](https://github.com/godot-jolt/godot-jolt/files/12444739/bug.zip)

I encountered this edge case when trying to make a "preview system" for where a placed structure will exist, kind of like the TF2 engineer.

The relevant code:
```
var trace = Trace.new()
var start = Vector3(3.62377, 0.750888, -7.950927)
var end = Vector3(4.046801, 0.750888, -6.118727)
var shape = BoxShape3D.new()
shape.size = Vector3(0.8, 1.4, 0.8)
trace.standard(start,end, shape, self, 1)
print("Faulty Collision results (no collision): ", trace.results)
```
where trace.standard is the following wrapper
```
func standard(origin : Vector3, dest : Vector3, shape : Shape3D, e, mask):
	var params : PhysicsShapeQueryParameters3D
	var space_state
	
	# Create collision parameters
	params = PhysicsShapeQueryParameters3D.new()
	params.set_shape(shape)
	params.transform.origin = origin
	params.set_collide_with_bodies(true)
	params.set_exclude([e])
	params.set_motion(dest - origin)
	params.set_margin(0.04)
	params.set_collision_mask(mask)
	
	hit = false
	
	# Get distance fraction and position of first collision
	space_state = get_world_3d().direct_space_state
	results = space_state.cast_motion(params)
	
	if !results.is_empty():
		fraction = results[1]
		endpos = origin + (dest - origin).normalized() * (origin.distance_to(dest) * fraction)
	else:
		fraction = 1
		endpos = dest
		return # didn't hit anything
	
	hit = true
	
	# Set next parameter position to endpos
	params.transform.origin = endpos
	
	# Get collision normal
	results = space_state.get_rest_info(params)
	if !results.is_empty():
		normal = results.get("normal")
	else:
		normal = Vector3.UP
```

**Comment by mihe** [comment]
Happens with Godot Physics as well.

Your cast box is already overlapping with the wall at the start, and as mentioned in [the documentation](https://docs.godotengine.org/en/stable/classes/class_physicsdirectspacestate3d.html#class-physicsdirectspacestate3d-method-cast-motion) for `cast_motion` it ignores any initial overlaps. You need to do a `get_rest_info` (or `collide_shape`) to check for those.

**Comment by Gamepro5** [comment]
I see. Taking the rest info first to prematurely stop it does seem to fix that, but it doesn't seem to fix the case where `start = (3.472787, 0.750426, -6.399817)` and `end = (4.100426, 0.750426, -8.065163)`.
```
trace.rest(Vector3(3.472787, 0.750426, -6.399817), shape, self, 1)
print(player.global_position, planned_position)
if trace.hit:
     return
```

**Comment by mihe** [comment]
I'm not sure what you mean by "fix" in this case. The box isn't overlapping with anything at that position, so `get_rest_info` won't report a hit.

**Comment by Gamepro5** [comment]
[bug.zip](https://github.com/godot-jolt/godot-jolt/files/12446836/bug.zip)
I mean something like this, where both the `get_rest_info` and `cast_motion` don't report a hit.

**Comment by mihe** [comment]
You're using a margin of 0.04 with `cast_motion`, but no margin with `get_rest_info`, while being just under 0.04-ish meters away from the wall, meaning you get an initial overlap with `cast_motion` and thereby no hit, and no hit with `get_rest_info` either.

Weirdly enough Godot Physics disagrees here, which seems to be because they effectively ignore the `margin` parameter during `cast_motion`, which when looking at the code seems to be a bug. They only use `margin` to inflate the AABB for the initial broadphase culling, but then don't use `margin` for the actual collision checks in the binary search, making the inflated AABB pointless to begin with.

Anyway, just use the same margin for both `cast_motion` and `get_rest_info` and it should work as expected.

**Comment by Gamepro5** [comment]
That godot physics difference is very odd, thank you so much for the diagnosis doc.
