### ISSUE TITLE
Project Settings not being maintained/requiring relaunch

### ISSUE THREAD

**Issue by Bimbam360** [godot-jolt/godot-jolt#583]
Platform: Windows 11 / Godot 4.2 Dev 4 (I know, sorry)

It appears several, possibly all project settings for Jolt 3D do not take effect until the editor is restarted.

Easy enough to test by trying to tweak sleep settings and getting no change until a restart.

**Comment by mihe** [comment]
I'm fairly confident that this is not an issue with this extension, and rather a general problem with Godot. It's not really something that I can mess up in the first place, as far as I know.

I've noticed when changing many project settings that the actual saving of them won't take effect until you've mashed the save button a couple of times, although it's not perfectly consistent across all settings for some reason.

An easy/obvious way to test it is by changing something like the `Display > Window > Mode` setting and the running the application. I always end up with the old display mode on the first run, unless I save like 3+ times before running, but then the setting will typically apply on the second run.

I'm seeing the same behavior when changing the sleep settings of this extension. Let me know if that sounds similar to what you're observing.
