### ISSUE TITLE
`Area3D` doesn't report overlaps when enabling `monitoring`

### ISSUE THREAD

**Issue by Regrad** [godot-jolt/godot-jolt#584]
Good afternoon. If an object is in the "Area3D" zone with monitoring turned off, then when monitoring is turned on, Area does not detect the body. This works fine in GodotPhysics.

How to repeat:

Place Area3D, turn off monitoring, place the body in it and then turn on monitoring in GDScript. When turned on, the body is not detected.

**Comment by mihe** [comment]
Thank you for reporting this.

That is indeed a bug, and a fairly sloppy one that I thought I actually supported.

It should be easy to fix though.

**Comment by Regrad** [comment]
Thank you. By the way, I don’t know where I can write to you, so I’ll write here. Here's a game that uses Jolt. I want to thank you for taking care of it. Without your work, we wouldn't be able to make our game good enough. If you want, you can mention our game as an example of use in a completed medium-large game.

https://godotforums.org/d/35814-hellbringers

**Comment by mihe** [comment]
That's pretty neat! Thank you for sharing.

**Comment by mihe** [comment]
The fix for this is included in the newly released [0.8.0-rc1](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.8.0-rc1). If you're able to, I'd appreciate it if you could give that release a try and report back whether it solves the issue for you.

**Comment by Regrad** [comment]
It works now! Thank you!

**Comment by mihe** [comment]
The fix for this is now also included in the newly released [0.8.0-stable](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.8.0-stable).
