### ISSUE TITLE
Add support for Godot 4.2

### ISSUE THREAD

**Issue by mgrigajtis** [godot-jolt/godot-jolt#600]
Attempted to load this plugin in Godot 4.2, crashed on open.

**Comment by mihe** [comment]
As stated [in the README](https://github.com/godot-jolt/godot-jolt#what-versions-of-godot-are-supported), I only support the latest stable version of Godot. Development versions are moving targets with potentially breaking changes that I have no interest in keeping up with.

Support for 4.2 will be added when 4.2-stable is released some time in early November.
