### ISSUE TITLE
Performance is lower than Unity/PhysX

### ISSUE THREAD

**Issue by Saul2022** [godot-jolt/godot-jolt#610]
System Lenovo ideapad 3 8GB ram

IGPU with amd radeon vega 3  graphicsdriver

It seems that while engines like the physx from unity  have fps more stable than the jolt physics one, even if exporting as a release build  it still got that   framerrate, 

repro: 
[physics-test1.zip](https://github.com/godot-jolt/godot-jolt/files/12716973/physics-test1.zip)

note that both are using 2.4k rigid boxes on box collision shape.

will post videos later on, in phone.

Edit got it (not that it without lighting and post effect 

https://github.com/godot-jolt/godot-jolt/assets/97898580/d3ca98bf-acbe-4e9a-94b9-5ddb40b64cc1

Unity 

https://github.com/godot-jolt/godot-jolt/assets/97898580/78f71faa-9bf2-4c80-9c4a-8ec60c0ce410

**Comment by Saul2022** [comment]
> So, just to clarify, you are in fact able to export a build and run it? On Twitter [you mentioned](https://twitter.com/Saulcava1/status/1706225321689718870) that "jolt doesn’t work" when you export, so I'm a bit confused.

Yea, the  build i used from twitter was the 0.6.0 version which doesn’t seem to work, but installing the 0.7.0 works and i can export, sadly not much fps diference.

**Comment by mihe** [comment]
> the 0.6.0 version which doesn’t seem to work, but installing the 0.7.0 works

Strange. I'm able to export with both. Which version of Godot are you using?

**Comment by Saul2022** [comment]
> Strange. I'm able to export with both. Which version of Godot are you using?

4.1.1 stable in both, though i am starting to feel it because it was because i have to jolt addoms.

**Comment by mihe** [comment]
Alright. Well, I'm glad to hear your exporting problem worked itself out somehow.

As for the reported performance discrepancy with Unity/PhysX, I don't think this is going to be a particularly useful issue to have open, as it's a fairly arbitrary benchmark with no realistic means of resolving it.

Not only are we comparing two different physics engines that might potentially be set up with different settings (like the amount of solver iterations), and which might scale very differently in different scenarios, we're also (more importantly) comparing two completely different game engines with presumably wildly different architectures. There are many different factors at play here.

If someone decides to integrate PhysX into Godot at some point in the future, or some other 3D physics engine, then we can start making some more interesting comparisons I guess, but even then I'm not sure it's a great idea to choose your physics engine based on the number of boxes you can pile up.

**Comment by Saul2022** [comment]
I understand though, i see it kinda weird how unity can handle all that though it has 10 solver iterations while jolt 16 
![Captura de pantalla 2023-09-25 220009](https://github.com/godot-jolt/godot-jolt/assets/97898580/2644f8fe-c00a-4c29-8044-f2d06970c5d7)
