### ISSUE TITLE
[MacOS] Engine crashes when loading a project with Godot Jolt installed

### ISSUE THREAD

**Issue by spitemonster** [godot-jolt/godot-jolt#619]
Have been interested in testing this out after some issues I've been having with the internal physics engine but installing it in both an active project as well as a fresh project on my Macbook Pro crashes the engine before it launches. Attached is the crash report. Would love to fix this and get into open source stuff but no idea where to even start!

[cr.txt](https://github.com/godot-jolt/godot-jolt/files/12754763/cr.txt)

**Comment by mihe** [comment]
Your crash report seems to indicate that you're using Godot 4.2, which is technically not not supported by this extension, as mentioned in [`README.md`](https://github.com/godot-jolt/godot-jolt#what-versions-of-godot-are-supported).

Could you check whether it crashes when you use [Godot 4.1.1](https://github.com/godotengine/godot/releases/download/4.1.1-stable/Godot_v4.1.1-stable_macos.universal.zip) instead?

**Comment by spitemonster** [comment]
Oh gosh I’ll be so embarrassed if I didn’t read the dang README. Let me get back to you but assume you’re good!

**Comment by spitemonster** [comment]
My sincere apologies, you're totally correct. Issue closed.
