### ISSUE TITLE
Larger `ConcavePolygonShape3D` are slow to create

### ISSUE THREAD

**Issue by mihe** [godot-jolt/godot-jolt#621]
When using a `ConcavePolygonShape3D` that contains a lot of triangles (~450k in this case), both the editor and game can be quite slow to load.

Here's how to reproduce it:

1. Download this project: [slow_concave_shape.zip](https://github.com/godot-jolt/godot-jolt/files/12766884/slow_concave_shape.zip)
2. Download Godot Jolt (omitted due to size limit): [godot-jolt_v0.8.0-stable.zip](https://github.com/godot-jolt/godot-jolt/releases/download/v0.8.0-stable/godot-jolt_v0.8.0-stable.zip)
3. Download its debug symbols (if you're going to profile): [godot-jolt_v0.8.0-stable_symbols.zip](https://github.com/godot-jolt/godot-jolt/releases/download/v0.8.0-stable/godot-jolt_v0.8.0-stable_symbols.zip)
4. Add Godot Jolt (and its symbols) to the project
5. Load the project in the editor
6. Restart the editor if prompted
7. Close the editor
8. Run the main scene from command-line (using `/path/to/godot path/to/main.tscn`)
9. Note the load times
10. Switch the physics engine to Jolt
11. Run the main scene from command-line again
12. Note the increased load times

Running it through Superluminal shows that most of the overhead when comparing to Godot Physics (28 seconds in this case) is spent in `JPH::Indexify`.

![image](https://github.com/godot-jolt/godot-jolt/assets/4884246/5e915768-dae8-4c06-ab15-e5b517ad626c)

**Comment by mihe** [comment]
I'm curious what your take is on this, @jrouwe. I realize this code path was probably never meant to be called at runtime, but I'm not quite sure what the alternative is, given that Godot gives me a list of non-indexed vertices with no good way of caching anything that I'm aware of.

I assume that going the non-optimal route of just giving each face its own indices would completely wreck `MeshShape::sFindActiveEdges`?

**Comment by mihe** [comment]
I also realize that this is an extreme example, of course, but I figured it should be brought up at least to see if there's any low-hanging fruit in terms of gains here.

**Comment by jrouwe** [comment]
The ```Indexify``` function is O(N^2) so slow indeed. The other parts of the mesh creation process already got a pass so are much faster than they were initially (see https://github.com/jrouwe/JoltPhysics/issues/137#issuecomment-1119679404).

If you know an algorithm that can snap nearby vertices and create index/vertex buffers then I'm interested (I was thinking spatial hashing, but you'd still need to search a number of cells per vertex so I'm not sure how much faster it would be).

**Comment by a-day-old-bagel** [comment]
par_shapes.h of [the Par library](https://github.com/prideout/par/tree/master) uses binning for its weld function in a way that I _think_ might be better than a naive N^2.

So it drops the points into bins (O(N)) and then for each point checks the bins again (another O(N) since number of bins checked should be much smaller than N and not dependent on N). It only has to check a few bins because, like you suggested, it's doing something equivalent to spatial hashing. I think by tweaking the epsilon value that determines bin size, the user can optimize how many bins are checked for their specific mesh.

Correct me if I'm doing big-o all wrong though. That certainly does happen to me sometimes.

[Here is the relevant code section.](https://github.com/prideout/par/blob/master/par_shapes.h#L1651)

**Comment by jrouwe** [comment]
I did it slightly differently:

https://github.com/jrouwe/JoltPhysics/pull/721

@mihe it needs a bit more testing to validate that it is completely correct, but I think the running time of this new algorithm is close to O(N)

**Comment by mihe** [comment]
Interesting approach! That looks quite quicksort-y to me. Wouldn't the divide-and-conquer nature of this make it something like O(N log(N))? Either way, that is quite the speedup indeed. It went from 28 seconds to 219 milliseconds on my machine. That should certainly be quick enough to satisfy most use-cases.

**Comment by mihe** [comment]
> it needs a bit more testing to validate that it is completely correct

I can at least confirm that the repro above results in the exact same vertices/indices as the O(N^2) approach. Same goes for any weirdly triangulated CSG shape that I throw at it.

**Comment by jrouwe** [comment]
> Wouldn't the divide-and-conquer nature of this make it something like O(N log(N))?

Yes, you're right, it is N log(N). I didn't realize the tree traversal added a log(N). Actually it can still be O(N^2) if you put all vertices in 1 point, but spatial hashing would have done the same for that case.

> I can at least confirm that the repro above results in the exact same vertices/indices as the O(N^2) approach. Same goes for any weirdly triangulated CSG shape that I throw at it.

Thanks for confirming! I did a bit of extra testing too and found a few minor issues. I've merged the changes into master.
