### ISSUE TITLE
Provide more detailed access to current state of joints (from gdscript / C#)

### ISSUE THREAD

**Issue by i-draw-boxes** [godot-jolt/godot-jolt#638]
I recently started trying out jolt in combination with godot. So far I have to say I am quite impressed how smooth the transition was. However, there is one thing I would like to see improved with the API of the Jold-specific node types.

## Access to current angles / offsets of springs
For certain games it could be beneficial to read how far off a spring is from its rest angle/position (or access to the current angles in joint-space). If I understand it correctly, this information is available from Jolt and could be retrieved via properties or functions in gdscript and C#. 

This could be used to simulate elastic vs. plastic deformation (by setting new rest angles after deformation).

Again, thank you for making this awesome addon for the Godot engine.

**Comment by mihe** [comment]
This was requested in #598 already, so I'll go ahead and close this and defer to that discussion.
