### ISSUE TITLE
Is there a way to find out if a JoltGeneric6DOFJoint has reached the angular limit?

### ISSUE THREAD

**Issue by Griiimon** [godot-jolt/godot-jolt#647]
I'm using a 6DOFJoint with an angular motor and angular limits. When the joint reaches the angular limit I want to disable or lock (velocity 0) the motor so it doesnt keep pushing against the limit, because this sends little irregular "shivers" through my bodies.

**Comment by mihe** [comment]
No, there's not. This has sort of been requested already in #598, so I'll go ahead and close this and defer to that discussion.
