### ISSUE TITLE
Ray-casts using `hit_from_inside` don't return a zero normal from inside convex shapes

### ISSUE THREAD

**Issue by firescaleVR** [godot-jolt/godot-jolt#652]
A raycast starting inside a solid body is reporting the normal of the first surface it hits instead of (0,0,0) like godot physics reports.
It reports the correct collision point which is the starting point of the ray, just not the right normal.
A trivial issue I know since I can just check if the collision point == starting point.

**Comment by mihe** [comment]
I'm assuming we're talking about ray-casts using `hit_from_inside`?

If so, then this is indeed a discrepancy with Godot Physics that I somewhat deliberately ignored when I implemented ray-casting. In hindsight I should probably have committed to the discrepancy properly by actually documenting it at least.

@jrouwe, I'm looking at how Jolt's `mTreatConvexAsSolid` parameter is implemented, and I'm getting the sense that `RayCastResult::mFraction` is pretty much guaranteed to be zero when hitting a solid from inside, and guaranteed to be non-zero when not. Is this assumption correct? If so, then this would be trivial to fix I guess.

**Comment by jrouwe** [comment]
> I'm getting the sense that RayCastResult::mFraction is pretty much guaranteed to be zero when hitting a solid from inside

I think you're right.

**Comment by mihe** [comment]
Apologies for the long wait, but the fix for this is included in the newly released [0.10.0-rc1](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.10.0-rc1).

If this is still relevant to you then I'd appreciate it if you could give that release a try and report back whether it fixes the problem for you.
