### ISSUE TITLE
Raycasts w/ Godot Jolt don't propagate when reflecting/bouncing

### ISSUE THREAD

**Issue by yosimba2000** [godot-jolt/godot-jolt#661]
MRP attached. It is Godot 4.1.2 .Net version, using C#. WASD to move, mouse to look.
[godot jolt raycast issue.zip](https://github.com/godot-jolt/godot-jolt/files/13196816/godot.jolt.raycast.issue.zip)

I want to propagate a raycast by casting a ray, recording the hit point and hit normal, then bounce that raycast from the last hit point according to the hit normal.

The issue is that in Godot Jolt, the raycast only casts from the camera position to one hit point. When it tries to bounce the ray from the first hit point, it fails to make a new ray because the 2nd raycast detects that it hits the same hit point as the first ray, and thus the ray fails to propagate.

The resulting hit points and hit normals are GD.Printed(). When using Godot Jolt, only two hit points are ever achieved, with the 2nd hit point always hitting the same as the 1st hit point. So basically the 2nd propagation hits the same location it started at.

Doing the raycasts in Process() vs PhysicsProcess() shows no difference.

Rays are colored red to show successfully created rays. There is only 1 ray produced, instead of many. The room is created from a single cube in Blender with its normals inverted so that I can use the interior of the cube as a room. The cube is given a collider using Trimesh Static Body option.

When switching physics to Godot Physics, you get the possibly related issue where the rays do bounce, but they escape the watertight room when the ray origin is close to an intersection where the cube faces meet.
https://github.com/godotengine/godot/issues/84108

**Comment by yosimba2000** [comment]
Did some more testing and I think I found part of the issue.

In Godot Jolt, if the origin of the raycast lies directly on the surface of a collider, as is reported from the raycast hit point, then raycasting from that position will cause the raycast to hit that raycast origin.

I found that if you offset the raycast origin by a small value, then the raycast origin no longer lies on the surface of a collider, and will propagate correctly.

So what I've done is record the hit position and reflection direction of each ray, then for the next ray, it's origin will not be from the last hit point, but rather `(the last hitpoint)+(small float value)*(reflection direction)`
```

offset = refDir*0.001f;
PhysicsRayQueryParameters3D physicsRayQueryParameters3D = PhysicsRayQueryParameters3D.Create(current+offset,current+refDir*1000f);

```
However, it still does not resolve the issue of raycasts escaping watertight meshes through face intersections.

Diagram

**Comment by mihe** [comment]
Does this give you the result you expect? (I find it hard to tell)

```cs
physicsRayQueryParameters3D.HitBackFaces = false;
```

**Comment by yosimba2000** [comment]
> Does this give you the result you expect? (I find it hard to tell)
> 
> ```cs
> physicsRayQueryParameters3D.HitBackFaces = false;
> ```

No, both HitBackFaces=false and HitBackFaces=true did not resolve. Since I inverted the normals of the cube in Blender, the normals of the cube faces should now point inside the cube.

**Comment by mihe** [comment]
That's very odd. I can see it bouncing around just fine in your MRP if I just set `HitBackFaces` to `false` (which is `true` by default) just before `IntersectRay` is called. In fact, with Godot Physics it eventually stops after 2-3 seconds regardless of what `HitBackFaces` is set to, whereas with Godot Jolt (with `HitBackFaces` set to `false`) it just keeps bouncing around seemingly forever.

> Since I inverted the normals of the cube in Blender, the normals of the cube faces should now point inside the cube, and so the cube back faces would be pointing outwards.

My thinking was that the ray-cast hits sometimes maybe end up ever so slightly on the outside of the cube, and thus the next ray would originate from outside and thereby hit the back-face of the triangle. As such, it seemed like a good idea to have `HitBackFaces` set to `false`.

**Comment by yosimba2000** [comment]
Oh sorry you are right! I added HitBackFaces after IntersectRay() on accident! Looks like that clears it up. 

Do you know if raycasting adds a stepsize each frame? So frame 1 starts at position1 on the ray, then frame 2 starts at position1+rayStepSize?

**Comment by mihe** [comment]
> Oh sorry you are right! I added HitBackFaces after IntersectRay() on accident! Looks like that clears it up.

Glad to hear it! I guess we can consider this resolved then? I don't think Godot makes any guarantees about which side of the face a ray-cast hit is meant to end up on.

> Do you know if raycasting adds a stepsize each frame? So frame 1 starts at position1 on the ray, then frame 2 starts at position1+rayStepSize?

I'm not sure I follow. What do you mean by step size? Ray-casts are done immediately in their entirety, and not incrementally over several frames, if that's what you mean.

**Comment by yosimba2000** [comment]
Yes, I think it's resolved, thank you so much!

In my mind, I thought raycasts were kind of like this:
1) For a raycast, it has an origin and direction.
2) Create ray that starts from Origin and ends at Origin+Direction*StepSize*1.
3) If ray intersects nothing, create another ray starting from Origin and ending at Origin+Direction*StepSize*2
4) If ray intersects nothing, create another ray starting from Origin and ending at Origin+Direction*StepSize*3
5) Keep incrementing the multiplier on StepSize until detect intersection, or end position is exceeded.

But I guess there are exact triangle/plane/ray intersection equations that can be solved without step sizes :)

**Comment by mihe** [comment]
> But I guess there are exact triangle/plane/ray intersection equations that can be solved without step sizes :)

Yes, I believe this is the case.

I'll go ahead and close this then.
