### ISSUE TITLE
Low speed object tunneling

### ISSUE THREAD

**Issue by AndreVallestero** [godot-jolt/godot-jolt#681]
Low speed tunneling with godot-jolt. My setup is as follows:

- C#
- 8000 1m\*1m\*1m falling cubes, managed by physics server
- 64m\*8m\*64m static body platform

I've attached a video and the minimal reproduction: 

[godot-jolt-tunneling.webm](https://github.com/godot-jolt/godot-jolt/assets/39736205/4ae1bd68-aac2-42ed-9566-2e07c77d582b)

[godot-physics-benchmark-jolt-physics.zip](https://github.com/godot-jolt/godot-jolt/files/13340660/godot-physics-benchmark-jolt-physics.zip)

**Comment by mihe** [comment]
If you check Godot's Debugger output when the bodies start falling through the floor you'll see why:

![Debugger Output](https://github.com/godot-jolt/godot-jolt/assets/4884246/0132862b-04ba-4e19-9c06-88063ba66c47)

Just bump up those limits in the project settings and things should work a lot better.
