### ISSUE TITLE
Game freezes after some time

### ISSUE THREAD

**Issue by kaenganxt** [godot-jolt/godot-jolt#684]
In a game project where I'm using Godot Jolt, the game randomly freezes in a certain 3D scene and can only be killed afterwards.
This only seems to happen on Linux, but not on Windows.

When freezing, the following message is shown in the log which brings me to the idea that the issue could be caused by Godot Jolt (although I'm not sure):
> WARNING: Godot Jolt's job system exceeded maximum number of jobs. This should not happen. Waiting for jobs to become available.

Since I'm not really sure what causes this, do you have any advice on how I could debug this further?

Using Godot v4.1.3.stable.arch_linux (On KDE with Wayland) with Godot Jolt 0.10.0 from the Asset library.

**Comment by mihe** [comment]
That's not good.

> the game randomly freezes in a certain 3D scene

Can you give me any specifics about that particular scene? Is there anything unusual happening in it?

**Comment by kaenganxt** [comment]
I managed to track it down a little bit more: The 3D scene contains a user interface overlay. This user interface overlay contains a SubViewport with another 3D scene inside (in a separate world). This SubViewport is then displayed as a texture in a TextureRect.

If I remove the SubViewport, the game never freezes.
Also, if the world inside the SubViewport is empty, the game also doesn't freeze.

I'll further try to see if certain settings can prevent this issue from happening.

**Comment by mihe** [comment]
Right, I was somewhat afraid that it was going to be related to separate worlds.

Having separate worlds means having separate physics spaces, which both share the same job system in Godot Jolt. This should in theory not be a problem, but it's definitely a code path I haven't tested all that much myself, especially not on anything other than Windows, so there might be dragons.

This is then likely the same bug as #554, which also happened to be on Linux. Sadly that one wasn't reproducible outside of a very specific scene, so we just sort of chalked it up to a random occurrence and left it at that, but clearly this is an actual problem.

Is there any chance you'd be able to share something similar to that scene of yours with the SubViewport? It would make things a million times easier if I was able to reproduce this myself somehow, even if it's not 100% reproducible.

**Comment by kaenganxt** [comment]
I reduced the problem to a smaller reproducible example: https://cloud.anura.team/s/TpGtJt454jRBS3b
This now consists of a static scene with an overlay. This overlay has several viewports, each with a static body inside.
When launching this setup on Linux, it freezes after a random amount of time (mostly between 1 to 60 seconds).

**Comment by mihe** [comment]
Thank you! That helped me reproduce it on Windows even.

It turned out to be a dumb mistake on my part, where I don't actually reclaim any of the jobs inbetween stepping the individual physics spaces/simulations, so if you had enough active physics spaces/simulations (30 in this case) you would inevitably run out of jobs.

With that said, having a unique world (and thus a unique simulation) for every single thumbnail in an editor like this strikes me as a fairly expensive thing to do, although I haven't looked at any profiling for it, but I would at the very least recommend that you have your viewport do something like:

```gdscript
extends Viewport

func _ready():
	PhysicsServer3D.space_set_active(find_world_3d().space, false)
```

... to prevent having to pay the cost of stepping a simulation that's never going to be used for anything dynamic anyway.

**Comment by kaenganxt** [comment]
Thanks! Also for the hint about disabling physics.
