### ISSUE TITLE
Godot 4.2 RC 1 crashes on mac when godot jolt is in project folder

### ISSUE THREAD

**Issue by thmasn** [godot-jolt/godot-jolt#687]
not sure if 4.2 is supported yet, but when i try to open a project which uses godot jolt in godot 4.2 RC1, the editor crashes when loading the project.

full error report:
[error.txt](https://github.com/godot-jolt/godot-jolt/files/13397028/error.txt)

**Comment by mihe** [comment]
What version of Godot Jolt are you using? Any compatibility issue with 4.2 should have been resolved as of version 0.9.0.

With that said, I only officially support the latest stable version of Godot, so if it still doesn't work after you update to the latest version (0.10.0) then you'll just have to wait until I've released a version that's compatible with the eventual 4.2-stable.

**Comment by thmasn** [comment]
i updated to jolt 0.10, and everything works. seems like that was all i needed. sorry for the troubles.
