### ISSUE TITLE
Reparenting with `keep_global_transform` doesn't keep global transform

### ISSUE THREAD

**Issue by firescaleVR** [godot-jolt/godot-jolt#693]
Thanks for the fix to collision normals being reported from inside collision shapes, I haven't had a chance to test it yet; I've been wracking my brain on some other problems:

When using node.reparent(new_parent,true) with the flag set for keeping global position it has some odd behavior, in my main project the objects appear to go to (0,0,0) of the parent, in a minimal reproduction project they go somewhere else that's not (0,0,0).

To combat this I tried changing the global_transform of the object to position it back where it was after doing node.reparent(), but this had no effect 95% of the time. This is very odd asynchronous behavior. So I resorted to using await get_tree().process_frame before setting the object transform, this is not preferable as it causes unintended consequences with scripts waiting for the reparent script to finish.

None of this happens in default godot physics, with the flag set the objects stay in place and with the flag not set you can immediately position them/set velocity etc after the reparent and it works.

To reproduce:
1. Run the attached project and click with the mouse on the floor to spawn a cube
2. Move the camera with WASD Ctrl Space Arrow Keys to move the cube somewhere
3. Click the mouse on the floor again to parent the cube to the root node, the cube will fall in place as expected with godot physics
4. Install jolt and test the scene again, the cubes will go to a spot outside the platform when being reparented

[jolt test1.zip](https://github.com/godot-jolt/godot-jolt/files/13453665/jolt.test1.zip)

**Comment by mihe** [comment]
This is very strange.

What's especially strange is that it's seemingly random, which makes it difficult to debug. Even the act of stopping on a breakpoint seems to introduce enough time for something to correct itself, preventing the bug from manifesting, which smells like a race condition of some sort.

> When using node.reparent(new_parent,true) with the flag set for keeping global position it has some odd behavior, in my main project the objects appear to go to (0,0,0) of the parent, in a minimal reproduction project they go somewhere else that's not (0,0,0).

What it looks like to me is that the node randomly gets reparented as if `keep_global_transform` would be false, meaning only its local transform is preserved.

I'll need to do some more digging at another time. I'm really struggling to think what I could even have done wrong here. There's really not much I have control over in this scenario. I just move the body where Godot tells me. But as you point out I'm unable to reproduce this with Godot Physics, so clearly there must be some kind of discrepancy somewhere.

Very odd.

**Comment by mihe** [comment]
Well, I found it. Thankfully it was something specific to only this problem, and not the sign of a broader issue.

I'll try to have a new release out when Godot 4.2-stable is released.

**Comment by firescaleVR** [comment]
Awesome, thanks!
