### ISSUE TITLE
`get_contact_local_shape` returns the same index for all shapes

### ISSUE THREAD

**Issue by lemonJumps** [godot-jolt/godot-jolt#703]
Hi, I'm trying to implement a physics based damage and for that I need to know which shape has been collided with.

I've noticed that if multiple shapes are an instance a cylinder (car tire), under the same rigid body. when you use ```get_contact_local_shapes``` they all return the same shape ID.

The minimal setup to reproduce:
scene with static body collider and a box collision shape as the "ground"
and a rigid body with 4 box collision shapes at the same Y moved into a sort of square shape.

here's an example, the labels are created at contact local position and are offset up with each collision, the first number is the collision id and the second number is the shape id.

You can see that all collisions have shape id 3 until all of them touch ground at which point they're all 0.
![collison](https://github.com/godot-jolt/godot-jolt/assets/113813092/b8a6b124-e0ca-4603-9884-d010dc682f47)

I think that ```find_shape_index``` might be where the bug happens, it seems as if all the shapes share the same sub shape ids, which makes it so only one of them gets selected for all the contacts.

I've deduced this form having a car that has 6 colliders, a body collider (convex shape), a front collider (convex shape) and 4 wheels (cylinder)
body has the index 0, front has index 1, and the rest are wheels. whenever the wheels are touching the ground all of them have the same ID but the custom shapes still show up with their respective IDs

**Comment by mihe** [comment]
I can confirm that this is indeed the case.

It's very strange though. I feel like I couldn't possibly have misunderstood Jolt's `SubShapeID` to such an extent that disparate shapes within a `StaticCompoundShape` are meant to yield the same `SubShapeID`.

Maybe it's got something to do with me wrapping every shape in my own `JoltCustomUserDataShape` decorator shape or something.

I'll need to do some more digging.

**Comment by mihe** [comment]
Ah, I see now that the comment on `SetUseManifoldReduction` spelled things out even more clearly:

> If the application requires tracking exactly which SubShapeIDs are in contact, you can turn off manifold reduction. Note that this comes at a performance cost.

For some reason I had filed away this manifold reduction as "fixes certain edge-cases" rather than "don't have this enabled if you care about `SubShapeID`".

I'll have it fixed shortly.

**Comment by jrouwe** [comment]
> Ah, I see now that the comment on SetUseManifoldReduction spelled things out even more clearly:

Yes and that's why I just pushed a change in the comments to point to that function :)
