### ISSUE TITLE
collision shape ID issue has been re-introduced with update 0.11.0

### ISSUE THREAD

**Issue by lemonJumps** [godot-jolt/godot-jolt#718]
Hi,
The Issue from #703 has resurfaced in the update 0.11.0, it looks like it is currently caused by change in commit: 1a4569d0517a431c31e8563f001cea0b27a3f796

Prior to this I've used a self built version before this from 823bf60b5746a127ac87ccde2a4623e31370417f which has fixed the issue nicely.

I don't 100% understand the difference between JoltWritableBody3D and JPH::BodyInterface but I'm guessing that the change in manifold reduction now doesn't get written trough to the actual body and manifold reduction stays enabled.

Here is how the collision ids look like currently, collision index is on the left, before "==", and shape id is on the right:

https://github.com/godot-jolt/godot-jolt/assets/113813092/03330db7-e808-4b74-9e91-8e33ad913681

**Comment by lemonJumps** [comment]
To sanity check if the issue didn't happen because of other commits since 823bf60b5746a127ac87ccde2a4623e31370417f I have merged together code from both commits, see diff below, and this has fixed both issues, I'm now certain that 1a4569d0517a431c31e8563f001cea0b27a3f796 is where the issue reappeared. :D

```
diff --git forkSrcPrefix/src/objects/jolt_body_impl_3d.cpp forkDstPrefix/src/objects/jolt_body_impl_3d.cpp
index 0b28ededeefa804bfee810551dd969770de7d4dc..b7bf8d20a8471eed56308b2ddbbb933743bfa6cb 100644
--- forkSrcPrefix/src/objects/jolt_body_impl_3d.cpp
+++ forkDstPrefix/src/objects/jolt_body_impl_3d.cpp
@@ -448,6 +448,11 @@ void JoltBodyImpl3D::set_max_contacts_reported(int32_t p_count) {
 	JPH::BodyInterface& body_iface = space->get_body_iface();
 
 	body_iface.SetUseManifoldReduction(jolt_id, use_manifold_reduction);
+
+	const JoltWritableBody3D body = space->write_body(jolt_id);
+	ERR_FAIL_COND(body.is_invalid());
+
+	body->SetUseManifoldReduction(use_manifold_reduction);
 }
```

**Comment by mihe** [comment]
Would you be able to share that repro of yours? I can't reproduce this on my end.

Here's what it looks like for me, if I draw a line to the contact point and color the line based on the shape index:

https://github.com/godot-jolt/godot-jolt/assets/4884246/7a9f13af-e01f-4180-b8b0-7202e7238b07

So I end up with 4 contacts per box, and each box has its own unique color, as expected.

**Comment by lemonJumps** [comment]
Here, I've put it into a repo.
The dlls are from releases, from github.
https://github.com/lemonJumps/godot-physics-test

**Comment by lemonJumps** [comment]
ah, I'm stupid, sorry. I thought the 0.11.0 was released recently, but now I've looked at the tags.
I'm sorry for wasting your time.
