### ISSUE TITLE
godot-cpp fail to build on Windows due to encoding issue

### ISSUE THREAD

**Issue by lfxu** [godot-jolt/godot-jolt#735]
When building godot-jolt, I encountered issue:
```
E:\code\godot-jolt\build\windows-msvc-x64\External\Build\godot-cpp\gen\include\godot_cpp/classes/rich_text_label.hpp(110): error C2001: newline in constant
```

Then in the code I see:
```
	void push_list(int32_t level, RichTextLabel::ListType type, bool capitalize, const String &bullet = "•");
```

Knowing this must be an encoding issue. I resaved that cached `rich_text_label.hpp` file as UTF-8 with BOM, and the build succeeded.

I believe this is relevant to the machine's Windows locale settings, and can be solved by forcing UTF somewhere. Knowing nothing about cmake language, I'm posting this issue here. If desirable, please let me know where to forward this issue to.

**Comment by mihe** [comment]
Thank you for reporting this.

It seems I had forgot to add the `/utf-8` flag to my godot-cpp fork, which causes MSVC to treat BOM-less files as UTF-8 as opposed to using whatever codepage Windows is set to default to.

I'll have it fixed shortly.
