### ISSUE TITLE
Need to add ```-mfpmath``` commandline option to 32-bit Linux builds

### ISSUE THREAD

**Issue by jrouwe** [godot-jolt/godot-jolt#739]
While adding a build for 32-bit Linux to detect the breakage you found in jrouwe/JoltPhysics#844, I found that just adding ```-m32``` to the ```CMAKE_CXXFLAGS``` as you're doing here:

https://github.com/godot-jolt/godot-jolt/blob/e6150dac64f308b2ca5877c1b574c66ecba77e46/CMakePresets.json#L193-L195

is not enough. I needed to add ```-m32 -msse2 -mfpmath=sse``` in order to successfully run the unit tests.

Without the ```-mfpmath``` flag the compiler starts to generate [387 floating point instructions](https://www2.math.uni-wuppertal.de/~fpf/Uebungen/GdR-SS02/opcode_f.html) (you know the ancient ones that use a stack and have higher intermediate precision). This completely destroys the collision detection algorithms because part of ```a * b - c * d``` is calculated at higher precision so even if ```round_to_float32(a * b) == round_to_float32(c * d)``` the result could be non-zero. When using SSE, Jolt turns off fused multiply add instructions in sensitive areas, but with 387 instructions that doesn't work.

**Comment by mihe** [comment]
Yeah, I saw your change and had the same change lined up already as a result. :)

Would it maybe make more sense for you to always add this on your end through `Jolt.cmake`, somewhere around [here](https://github.com/jrouwe/JoltPhysics/blob/0f191b7c14f14a5af833d951b1d5506c7e4b0646/Jolt/Jolt.cmake#L574-L586), seeing as how that flag is already implied to be `-mfpmath=sse` during 64-bit compilations, as seen [here](https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html#index-mfpmath-1)?

**Comment by jrouwe** [comment]
That's a better idea indeed. I'll make the change.

**Comment by jrouwe** [comment]
The change is ready to be integrated into godot-jolt.
