### ISSUE TITLE
MinimumOSVersion missing from Info.plist

### ISSUE THREAD

**Issue by adamwatters** [godot-jolt/godot-jolt#746]
When trying to distribute an iOS build I got the following error in Xcode. Looking at the Info.plist for the package - "MinimumOSVersion" is in fact missing. Lmk if I can send anything else to help - figuring out how to fix locally for now.

![image](https://github.com/godot-jolt/godot-jolt/assets/7673611/3c9ab176-56d7-4ba5-9324-7720e13e8d1a)

**Comment by mihe** [comment]
This was fixed in #712 and released as part of version 0.12.0-stable, so just updating (by reinstalling) should resolve the issue for you.

**Comment by adamwatters** [comment]
Awesome - thank you!!
