### ISSUE TITLE
Expose GetTotalLambdaPosition and GetTotalLambdaRotation

### ISSUE THREAD

**Issue by phelioz** [godot-jolt/godot-jolt#747]
The get_applied_force and get_applied_torque methods in Jolt joints currently return the applied force or torque as a float. It would be extremely beneficial to also have access to the full vector data (including direction and rotation) for these.

This enhancement would enable us to, for example, break joints in specific directions or apply the same amount of force, with direction, to other objects in the scene.

One solution could be to modify get_applied_force and get_applied_torque to return a Vector3. Users could then extract the length as currently done. Alternatively, create two new exposed functions for this purpose

**Comment by mihe** [comment]
I tried doing this when I first implemented these, but these lambda vectors aren't really meant to be interpreted that way, at least not across all joints. The single float was a compromise.

See jrouwe/JoltPhysics#629 for more details.

**Comment by phelioz** [comment]
I see, thanks for the info!
