### ISSUE TITLE
Stiffness option for springs in Jolt joints

### ISSUE THREAD

**Issue by phelioz** [godot-jolt/godot-jolt#748]
It would be great to be able to use stiffness or frequency for springs in the Jolt joints. While you can just use the regular joints if you want to use stiffness, these don't allow for breakable joints because you can't access the applied force / torque.

The frequency setting for springs in Jolt joints is fantastic for many situations, providing a specific type of behavior that works independently of mass.

However, stiffness becomes incredibly useful when simulating a certain kind of strength. By adjusting stiffness, you can effectively set a 'strength' level. This feature is particularly valuable when simulating something like a character's muscle strength or the lifting capability of a machine.

**Comment by mihe** [comment]
Yeah, this is something I've been thinking about for a while now as well. I think it's a good idea, and would probably be trivial to add. I just need to figure out some way of dynamically switching out the property fields based on which mode you set, but I've seen other nodes do that, so it probsbly shouldn't be too difficult.

**Comment by phelioz** [comment]
Object::_validate_property(PropertyInfo &p_property) and Object::notify_property_list_changed would probably be enough for dynamically switching out the property fields I think.

Like for example in the [Control](https://github.com/godotengine/godot/blob/master/scene/gui/control.cpp) class where some properties change depending on what the parent is.

**Comment by mihe** [comment]
That's pretty slick. `CSGShape3D` seems to rely on exactly that as well, for when you enable/disable collision on it.

I need to finish up soft bodies first, so it might be a little while before I get to this.

**Comment by phelioz** [comment]
Yeah `CSGPolygon3D` was a better example 😄 

No stress, nice to know it's planned.

**Comment by mihe** [comment]
With this extension now having been merged into Godot in the form of an engine module (see [README](https://github.com/godot-jolt/godot-jolt?tab=MIT-1-ov-file)), this extension will be considered to be in maintenance mode going forward, where only bug fixes will be considered for merging. As such, I'll go ahead and close this issue.

This will/should be addressed in the new Godot engine module instead, once we get some sort of mechanism for manipulating properties on the default joint nodes.
