### ISSUE TITLE
Velocity resets when an object is disconnected from joints.

### ISSUE THREAD

**Issue by JD-The-65th** [godot-jolt/godot-jolt#749]
Hey, I'm working on an XR interaction toolkit that uses joints to connect the hand to objects. When the joint is unset and disconnected from the object the hand is holding, it appears to lose all velocity while in Godot Physics it keeps its momentum.

**Comment by mihe** [comment]
I'm not able reproduce this issue from your description. In fact, I use this method for the picking in the example scenes camera, and when [unsetting the joint nodes](https://github.com/godot-jolt/godot-jolt/blob/8ed0ce5b86dbb218645e5db927a19d14241a1ad4/examples/scenes/common/scripts/free_look_camera.gd#L146-L156) it keeps the velocity just fine, allowing you to flick the objects away.

Would you be able to share a minimal repro project that showcases your problem?

**Comment by JD-The-65th** [comment]
Weird. I'll double check that the bug is reproducable in my project before providing a minimal project.

**Comment by jrouwe** [comment]
FYI, this very much sounds like: https://github.com/jrouwe/JoltPhysics/discussions/268

**Comment by JD-The-65th** [comment]
> FYI, this very much sounds like: [jrouwe/JoltPhysics#268](https://github.com/jrouwe/JoltPhysics/discussions/268)

That looks like exactly what I'm running into! I'm using the built in Generic6DOFJoint node but that looks to be the exact same.

**Comment by mihe** [comment]
Right, then I suspect you're likely making the same mistake I did when I first implemented the picking, by using a `StaticBody3D` as your hand. If you try using an `AnimatableBody3D` instead you should see better results.

**Comment by JD-The-65th** [comment]
Noted, testing out Jolt with this change.

**Comment by JD-The-65th** [comment]
Damn, can't test it inside my main project since it's in 4.3, but I'm gonna go ahead and assume that was the issue since I'm using StaticBody3D nodes. Closing.
