### ISSUE TITLE
AnimatableBody3D issue on Android

### ISSUE THREAD

**Issue by Badmintennis** [godot-jolt/godot-jolt#754]
Hi, i'm currently working on a coin pusher game and ran into some issues when exporting to Android.
I have a pusher block (AnimatableBody3d) moving in and out and some coins (RigidBody3d) that can land on top or get pushed by the AnimatedBody3d blocks if they land in front.
It all looks fine in the editor and PC executable, coins gets pushed smoothly by the pusher and the ones that land on top moves along with the motion.
However on Android this is what I get (please see gif below) the coins on top seem to have no friction and slide in place and the coins that get pushed in front of it seems to get pushed in small bursts rather than in a continuous motion.
I posted on discord about this and they suggested me to post here.

![jolt](https://github.com/godot-jolt/godot-jolt/assets/157423152/510cc2d4-aa25-4017-95a2-bc49ab8d5679)

**Comment by mihe** [comment]
Alright, I'll go ahead and close this for now. Let me know if you figure it out.
