### ISSUE TITLE
Raycast3D doesn't collide with RigidBody3D when ported to Quest VR

### ISSUE THREAD

**Issue by TheEmeraldWeegee** [godot-jolt/godot-jolt#769]
I am trying to make a system with raycasts where you can click a rigidbody cube and it hops away from you. This system works flawlessly when playing on computer, both screenmode and VR, but it doesn't work whenever I deploy it to android to test on my Quest 3. I have made a simple version with the same player controller as in my game, and the same yellow cube that should hop away once you click on it. There are indicators via a green crosshair on screenmode and green dots in VR to tell you if you are pointing at a clickable object. Again, this works perfectly on computer in my main project, both screenmode and VR, but it doesn't seem to work when deployed to standalone Quest 3.

The code for the VR raycast system can be found in the project folder, just find the Scripts folder, and then the Player folder. The script is called "VRController.gd", and the raycast code starts at line 322. For the screenmode raycast system, it is in the same folder as the VR controller script, but it's called "ScreenmodeController.gd", and the raycast code starts at line 120.

[Link to Project](https://drive.google.com/drive/folders/1GO27g2abpwSaYK1tXyQ1ZUfUfPIgMPrS?usp=sharing)

The videos attached below are from the project I am working on where this bug is occuring, but the project linked above is a simplified version that isolates the problem. I took the cube shown in the videos, and I transfered it to the linked project. In this isolated project, the problem happens with the computer version as well, but in my main project, it happens only on Android.
The top video shows what happens on computer, which is what is supposed to happen. The bottom video shows the exact same project but on quest 3 standalone.

https://github.com/godot-jolt/godot-jolt/assets/68498220/7ef42393-374c-4a8b-8469-52b1c9d71c69

https://github.com/godot-jolt/godot-jolt/assets/68498220/4227d4d8-160a-46de-b4f7-750fbb293fbe

Steps to reproduce:
- Download and open the project
- Launch it in VR (either PCVR or Quest Standalone, Quest Standalone is the problem)
- Get close to the cube and point either hand at it

What should happen:
- The raycast hits the cube and it shows a green dot indicating that you can interact with it
- You click the cube using the trigger, and it hops away from you

What actually happens:
- The green dots don't show up
- When enabling "Visible Collision Shapes" in the Debug tab, the raycast seems to not hit it at all.

**Comment by TheEmeraldWeegee** [comment]
I was able to fix the problem! Thanks to mihe, we were able to find out that I was changing the player's scale on the _ready() function to 0, which should not be done. I replaced the scale changes with disabling the processes, and it works! It even worked on Quest!

**Comment by mihe** [comment]
It was concluded through other channels that the issue here was using a zero scale in an attempt to disable one of the two `CharacterBody3D` that the player scene contained.

Changing it to toggle the bodies `process_mode` instead fixed the issue.
