### ISSUE TITLE
non-existent interface function

### ISSUE THREAD

**Issue by bk4928412** [godot-jolt/godot-jolt#770]
hi, im currently using godot 4.2 dev2 build and no matter what i do i cant get this plugin to work. the reason why i'm using 4.2 dev2 is because the newer versions is just doesnt work due to a bug on the engine side which i'm still waiting them to patch it.

anyway. it gives me an error and says

```

Attempt to get non-existent interface function: string_name_new_with_latin1_chars
D:/a/godot-jolt/godot-jolt/build/windows-clangcl-x64/External/Source/godot-cpp/src/godot.cpp:365 - Unable to load GDExtension interface function string_name_new_with_latin1_chars()
core/extension/gdextension.cpp:479 - GDExtension initialization function 'godot_jolt_main' returned an error.

``` 
now im wondering if this happens because im using the outdated version of godot. you may want to take a look at this issue and check if its related to godot. https://github.com/godotengine/godot/issues/85608

**Comment by mihe** [comment]
This extension is built against the GDExtension interface exposed by 4.2-stable, meaning it only supports that version as well as patch releases (4.2.x).

The function that you're getting errors about (`string_name_new_with_latin1_chars`) was added to the GDExtension interface roughly two weeks after 4.2-dev2 was released, so it makes sense that you'd get errors about it.

Unfortunately it just is what it is. It's technically possible to retarget the extension to work with your specific version of Godot (see instructions [here](https://github.com/godot-jolt/godot-jolt/blob/master/docs/hacking.md#updating-godot)) but it's unfortunately a fairly complicated process.
