### ISSUE TITLE
[Feature Request] Make it work for 2D

### ISSUE THREAD

**Issue by xerosugar** [godot-jolt/godot-jolt#774]
I'd like to see 2D support for this plugin. Default physics lacks some joint types and seems to be inaccurate at times from what I've seen.

**Comment by mihe** [comment]
Jolt is purely a 3D physics engine. There are other extensions out there that aim to implement the 2D physics API in Godot, like the Box2D extension for example.

**Comment by nadvornikjiri** [comment]
Is there any chance we could revisit this decision? The 2D alternatives like Box2D or Rapier2D provide some minor improvements but do not simulate well a chain or a rope and I don't think they ever will. Jolt physics has perfect rope simulation. They also have a much smaller community.

Modifying the GodotJolt to support 2D nodes seems so much easier than modifying the whole game to 3D nodes with fixed z axis (as for example, TileMaps don't exist in 3D, etc.) as a workaround...

**Comment by mihe** [comment]
> Is there any chance we could revisit this decision?

No.

> and I don't think they ever will

Rapier2D just got [a new solver](https://github.com/dimforge/rapier/pull/579) that should help with exactly this. Once the Box2D extension moves over to Box2D 3.0 (aka "Box2C") you should see a massive improvement there as well.
