### ISSUE TITLE
AreaBody3D don't detect RigidBody3D's with body_entered

### ISSUE THREAD

**Issue by justawhitecat** [godot-jolt/godot-jolt#786]
RigidBody3Ds are not detected by the `body_entered` signal, or the `area_entered` signal in AreaBody3D's, even if I toggle the "Areas detect Static Bodies."

They worked under Godot Physics.

**Comment by mihe** [comment]
Would you mind providing a repro? It seems to work just fine for me.

**Comment by justawhitecat** [comment]
Found the problem. In Godot Physics, collision shapes with one value as zero still lets you collide with it, but with Jolt the value must be above zero.

For example, if I have an Area3D with a width of 2, 3, 0.01, it will detect collisions. If it's 2, 3, 0, it wont detect any.

**Comment by mihe** [comment]
Right, yes. I should probably emit a warning for things like that. I've had other people run into other issues as a result of that as well.
