### ISSUE TITLE
Linux clang build doesn`t work

### ISSUE THREAD

**Issue by Nazarwadim** [godot-jolt/godot-jolt#815]
**System info:** Linux Mint 21.2 (Victoria) - X11.
**LLVM version:** 18.1.2
**Cmake version:** 3.22.1

**Error description:**
When using any of these commands to buid
```
cmake --build --preset linux-clang-x64-distribution
cmake --build --preset linux-clang-x64-editor-distribution
```
the following error occurs 
```
error: CMakeFiles/godot-jolt.dir/EditorDistribution/src/joints/jolt_cone_twist_joint_3d.cpp.o: Opaque pointers are only supported in -opaque-pointers mode (Producer: 'LLVM18.1.2' Reader: 'LLVM 14.0.0')
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

**Comment by mihe** [comment]
That's a strange error.

If I'm reading the error right it seems like you somehow end up compiling with LLVM 18 but linking with LLVM 14, which I don't quite understand how that's even possible. I've tried compiling with LLVM 18 myself and it seems to work just fine.

What's the output if you run `which clang` and `which ld.lld` respectively?

I suspect you'll probably be able to compile successfully if you disable LTO, but you'll likely take a performance hit by doing so. You can do this by passing `-DGDJ_INTERPROCEDURAL_OPTIMIZATION=OFF` to the configure command, so your build would look something like this instead:

```sh
cmake --preset linux-clang-x64 -DGDJ_INTERPROCEDURAL_OPTIMIZATION=OFF
cmake --build --preset linux-clang-x64-distribution
cmake --build --preset linux-clang-x64-editor-distribution
```

(You'll likely need to delete any existing `build` folder before running that first command again.)

Besides that workaround I'm not quite sure what else to suggest. Are you aware of anything special changes in your Linux environment that might affect something like this?

**Comment by Nazarwadim** [comment]
Wow, I didn't know `ld.lld` existed. The `sudo update-alternatives --install /usr/bin/ld.lld ld.lld /usr/bin/ld.lld-18 100` command fixed that. Before that, it was version 14. Also, I thought I had completely removed LLVM-14.
Thanks.
