### ISSUE TITLE
Increase precision of sliders for Contact Allowed Penetration and Contact Speculative Distance

### ISSUE THREAD

**Issue by MemoriesIn8bit** [godot-jolt/godot-jolt#832]
Hello! 

I've been working with Jolt for a while now and it's been working great, despite a lot of my Rigidbodies being smaller than the minimum recommended size (using spheres with a diameter of 0.05). The only problem I encountered was more an artificial one:
Both Contact Allowed Penetration and Contact Speculative Distance are (at my sizes) fairly limited in their accuracy, with their minimum value being 0.001. I am using 0.00035 and 0.0004 respectively and that works fine using ProjectSettings.set_setting calls, but I must admit, it would be nice to be able to set the values properly inside the Project Settings window. 
As stated, I work below the recommendations of the Readme, so I understand with more sane sizes, this is not a problem, so I can understand if the current limits remain enforced.

**Comment by mihe** [comment]
Apologies for leaving this one hanging for so long (I can't believe it's been a whole month already). I've been meaning to look into other means of achieving this, but this ended up pretty far down on my to-do list.

This is something that's a bit of a general problem with slider inputs in Godot, where the step size dictates the quantization of the value itself, which is somewhat unfortunate in my opinion. I feel like it should be possible to type in whatever value you want and only have it be clamped between min and max, and the step size should only dictate the values which the slider itself "snaps" to.

What you can do however is type in whatever value you want into your `project.godot` file, and that'll remain unchanged until you tinker with the value in the editor. That way you don't have to set it through code. It will however show up as 0 in the project settings editor in your case.

Anyway, I guess there's no real harm in changing the step size to something like 0.00001. I have a hard time seeing that it would serve as encouragement for using sizes outside of the stated conventions. I would imagine you're pushing it in terms of floating-point precision though, but if it works it works I guess.
