### ISSUE TITLE
Double-Precision-Engine crashes upon loading project

### ISSUE THREAD

**Issue by TheContainer** [godot-jolt/godot-jolt#844]
When godot is compiled with `precision=double`, the engine can't open any projects with Jolt inside.

Sadly, I cannot upload a minimal reproduction project because of the size of the project. So I describe the steps:
- Create a new project
- put godot Jolt inside
- load the project with double precision compiled godot

**Comment by mihe** [comment]
You currently need to build double-precision builds of Godot Jolt yourself, the instructions for which you can find [here](https://github.com/godot-jolt/godot-jolt/blob/master/docs%2Fbuilding.md).

Note that I haven't tested double-precision much, so there may be some rough edges with it still.

The next release of Godot Jolt will have pre-built double-precision binaries here on GitHub.

**Comment by TheContainer** [comment]
> You currently need to build double-precision builds of Godot Jolt yourself, the instructions for which you can find [here](https://github.com/godot-jolt/godot-jolt/blob/master/docs%2Fbuilding.md).
> 
> Note that I haven't tested double-precision much, so there may be some rough edges with it still.
> 
> The next release of Godot Jolt will have pre-built double-precision binaries here on GitHub.

Thanks for the quick reply.
