### ISSUE TITLE
CharacterBody-RigidBody collision is broken

### ISSUE THREAD

**Issue by TacoGuyAT** [godot-jolt/godot-jolt#845]
Godot v4.2.2.stable.mono.official [15073afe3] / Godot-Jolt 0.12.0

###### Highlight on 0:26
https://github.com/godot-jolt/godot-jolt/assets/35270005/7351bcc3-6962-4281-881f-7f095e7c7ad9

[sample.zip (without addons folder)](https://github.com/godot-jolt/godot-jolt/files/15280954/sample.zip)

There are similar issues for GodotPhysics, but I'm not sure if they're relatable: https://github.com/godotengine/godot/issues/49203, https://github.com/godotengine/godot/issues/31981

**Comment by mihe** [comment]
See #761.
