### ISSUE TITLE
Improve doc for using a non-stable version of godot

### ISSUE THREAD

**Issue by nonunknown777** [godot-jolt/godot-jolt#874]
I would like for example use for 4.3.x dev version, tried changing in cmake the GIT_COMMIT version but sadly it doesnt work, having a tutorial for how to build for dev versions for testing would be awesome!

**Comment by mihe** [comment]
When you say you've tried changing the `GIT_COMMIT`, do you mean you followed the steps mentioned [here](https://github.com/godot-jolt/godot-jolt/blob/40edf2c273f562ff708802ce3950c079f5dafeaa/docs%2Fhacking.md#updating-godot) or did you just happen upon that file and tried changing it?

I do need to update those steps to also mention [the version number](https://github.com/godot-jolt/godot-jolt/blob/40edf2c273f562ff708802ce3950c079f5dafeaa/cmake/GodotJoltVersionInfo.cmake#L16) that needs to be changed as well, but that version number is going away very shortly anyway, in favor of the `compatibility_maximum` version number that was added to the `.gdextension` format.

**Comment by nonunknown777** [comment]
ohh awesome, didnt saw this part for some reason... I'll try and give a feedback

**Comment by mihe** [comment]
I've updated the documentation to mention this new `compatibility_maximum` version number, and I also updated the documentation for the "proper" way of doing it as well.

The extension also targets 4.3 by default now, so you just need to build from source like normal, without changing any of this other stuff.

There should be a beta build here on GitHub very shortly as well.
