### ISSUE TITLE
version 0.13 beta1 doesnt open in brand new project

### ISSUE THREAD

**Issue by IPlayKindred** [godot-jolt/godot-jolt#889]
![image](https://github.com/godot-jolt/godot-jolt/assets/43112296/0d61432b-e34a-48fd-8437-b15e2a41f564)

tried importing it to a new project in godot 4.3 beta 1 gave me this list of errors.

something about pdb, which made me download the symbols version and copy the pdb from that and add to the extension windows file in my project but it still didnt work.

the rest is godot complaining that it cant load the extention.

**Comment by mihe** [comment]
Are you sure you're running it in Godot 4.3-beta1? The fact that it's complaining about `packed_vector4_array_operator_index` seems to suggest that you're using an older version of Godot than that, as that API was only added about a month ago.

**Comment by IPlayKindred** [comment]
oh nvm I was accidentally opening 4.3 dev 6, I appologize.

**Comment by mihe** [comment]
Oh! In the many, many hours I've spent in Godot I've somehow never noticed that version number in the corner before.
