### ISSUE TITLE
`Area3D` sometimes fails to detect `ConcavePolygonShape3D`

### ISSUE THREAD

**Issue by nagasawamaki** [godot-jolt/godot-jolt#897]
I have a character body 3d attached with a area 3d, and there is a static body 3d, with concave collision shape.
The area 3d sometimes cant detect it collide with the static body, as shown below:

Cant detect:
![螢幕擷取畫面 2024-06-12 143951](https://github.com/godot-jolt/godot-jolt/assets/24987226/2a2fe295-06ad-4f43-a1c6-f746b390ba03)

Can detect:
![螢幕擷取畫面 2024-06-12 144019](https://github.com/godot-jolt/godot-jolt/assets/24987226/1d3b9baf-2c16-4e5e-abbe-9dcd42d54788)

And I found that, if I remove below code in my character body 3d, it can always detect the static body.

```
	if not is_on_floor():
		velocity.y -= gravity * delta
```

I also found if I change to convex collision shape, it can always detect the static body too.

Thanks

Sample Project (without the addon, as it is too big):
[concave.zip](https://github.com/user-attachments/files/15799888/concave.zip)

**Comment by mihe** [comment]
For whatever reason it seems every triangle collision gets discard as being backfacing, which is strange.

This does mean that you can work around this by enabling the "Backface Collision" property on the `ConcavePolygonShape3D`, like so:

![image](https://github.com/godot-jolt/godot-jolt/assets/4884246/306321fd-f487-4437-984e-223f4410444b)

**Comment by mihe** [comment]
The `CharacterBody3D` and gravity was inconsequential. The important part seemed to be the Y-position of the `Area3D`, so I reduced the repro further: [BoxSensorVersusMesh.zip](https://github.com/user-attachments/files/15803767/BoxSensorVersusMesh.zip)

**Comment by mihe** [comment]
I've reported this upstream, as I'm pretty sure this is a bug in Jolt itself: jrouwe/JoltPhysics#1138

**Comment by nagasawamaki** [comment]
Thanks for your prompt actions!
Hope it will be fixed soon.

And in the mean time will try to enable the "Backface Collision" property.

Thanks!

**Comment by mihe** [comment]
It turned out that this wasn't really a bug in Jolt after all, but rather a mismatch of expectations.

This should be fixed by #899, which essentially forces `Area3D` to treat every shape as if "Backface Collision" was enabled.

**Comment by mihe** [comment]
[0.13.0-stable](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.13.0-stable) has just been released, which includes the fix for this.

Note that the release in the Godot Asset Library is still pending approval as of typing this, so you might need to download it from the link above.
