### ISSUE TITLE
Can move object

### ISSUE THREAD

**Issue by slime3000fly** [godot-jolt/godot-jolt#907]
When I have a VehicleBody3D with a large mass and a collision shape as a box, I can move it by touching the corner of the box. The problem is not with the GodotPhysics3D.

Video with Jolt:
https://github.com/godot-jolt/godot-jolt/assets/94618871/dc01a946-c62c-42b7-8ae4-408307065c5c

Video with GodotPhysics3D:
https://github.com/godot-jolt/godot-jolt/assets/94618871/0074d432-9188-406b-ba2f-51a0a9aa1002

Project to reproduce:
https://drive.google.com/file/d/1U58KE9y-ljNhF7sXp2CnBubaZeoEhS1p/view?usp=sharing

Godot version 4.2.2

**Comment by mihe** [comment]
I don't have the ability to test your project right now, but judging by the videos I'm assuming you're using `CharacterBody3D` along with `move_and_slide`?

Have a look at [this comment](https://github.com/godot-jolt/godot-jolt/issues/761#issuecomment-1913568126) and see if that helps you.

You might also see an improvement in this behavior if you upgrade to the latest pre-release, [0.13.0-beta1](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.13.0- -beta1), which targets Godot 4.3-beta, but you'll likely want to make the changes to your collision layer/mask setup that's mentioned in the issue I linked above anyway.

**Comment by slime3000fly** [comment]
Changing the layer/mask configuration helped with this problem, thanks. Also, the problem from [your comment](https://github.com/godot-jolt/godot-jolt/issues/761#issuecomment-1913568126) looks very similar to mine.
