### ISSUE TITLE
On a seam between two floors a player can be considered on a wall

### ISSUE THREAD

**Issue by v6stXN46WdLBtp** [godot-jolt/godot-jolt#918]
When there are two floors that are separate collision objects but at the exact same level the player can be considered on a wall.
This does not happen on godot's vanilla physics engine. In some player controllers this can completely stop the player.

_This project does not have godot-jolt added to decrease project size_
[BugRepro.zip](https://github.com/user-attachments/files/16263031/BugRepro.zip)
Directions: The player is teleported to the affected position on scene start, just press space over and over and you will see in the console that the player is being considered on the wall.

**Comment by mihe** [comment]
I am not able to repro this in [v0.13.0-beta1](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.13.0-beta1). It was likely fixed by #860.

**Comment by v6stXN46WdLBtp** [comment]
I forgot about checking beta versions. Sorry for the issue.
