### ISSUE TITLE
Shapes using a Dictionary to store data leak memory

### ISSUE THREAD

**Issue by jbromberg** [godot-jolt/godot-jolt#929]
Certain collision shapes have memory leaks originating from the Dictionary that is used to store their data. The simple script below illustrates the problem:

```gdscript
extends Node

# Leaks
func _process(delta):
	for i in 1000:
		var cap := CapsuleShape3D.new()

# Doesn't leak
func _process(delta):
	for i in 1000:
		var box := BoxShape3D.new()

```

**Comment by mihe** [comment]
I don't have the ability to test this for myself right at this moment, but do you see the same behavior if you use Godot Physics?

**Comment by jbromberg** [comment]
There is no leak using Godot Physics

**Comment by mihe** [comment]
[0.13.0-stable](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.13.0-stable) has just been released, which includes the fix for this.

Note that the release in the Godot Asset Library is still pending approval as of typing this, so you might need to download it from the link above.
