### ISSUE TITLE
JoltPhysics apply_torque() uses different transforms than GodotPhysics?

### ISSUE THREAD

**Issue by TrogerMester** [godot-jolt/godot-jolt#938]
I'm not quite sure in which coordinate system does the angular_velocity member of a RigidBody3D stores its value but after trying to understand this for a couple of days now i thought i might open an issue and see if someone could enlighten me on this.

Basically, when applying torque on one singular axis in global coordinates on a RigidBody3D in regular godot physics the angular velocity changes accordingly on that singular axis. In Jolt however, if the body is rotated then the angular_velocity will increase on multiple axises for some reason. I dont think this is right unless Jolt calculates stuff some other way.

I put the zip file for a minimal recreation project thing where u can test this for yourself. Rotate the object on an axis by inputting a direction and after some time reset the velocity by pressing SPACE. So far so good, Jolt shows correct velocity as far as u dont touch another axis. However, if you start rotating on another axis now the angular velocity changes on several other axises too. Change back and forth between Godot Physics and Jolt Physics to see the difference.  (I couldnt include the Jolt addon along with the project cus the file size got too big to upload here)

[Angular Velocity Test.zip](https://github.com/user-attachments/files/16627447/Angular.Velocity.Test.zip)

**Comment by mihe** [comment]
> I'm not quite sure in which coordinate system does the angular_velocity member of a RigidBody3D stores its value

It's in global-space.

> However, if you start rotating on another axis now the angular velocity changes on several other axises too.

I'm not quite sure I can see the problem. Since `angular_velocity` is in global-space, neither of the two transformations you're doing in the logging (multiplying by `basis` and `global_basis`) are applicable, so if I just focus on the logging of the actual value of `angular_velocity` it all seems to make sense to me with both Godot Physics and Jolt.

**Comment by TrogerMester** [comment]
> EDIT: If you're looking for the local-space angular velocity, `global_basis.inverse() * angular_velocity` should do the trick, or `global_basis.transposed() * angular_velocity` for a faster version if you know you have a `global_scale` of `(1, 1, 1)`.

ye this worked altough theres tiny precision errors when the angular velocity gets really high but i guess thats normal(?)
![image](https://github.com/user-attachments/assets/67bdef01-372d-4dc5-af85-49631069e77d)
here, torque is applied only on the local Y axis and the logged vector is the `global_basis.inverse() * angular_velocity`


> I'm not quite sure I can see the problem. Since angular_velocity is in global-space, neither of the two transformations you're doing in the logging (multiplying by basis and global_basis) are applicable, so if I just focus on the logging of the actual value of angular_velocity it all seems to make sense to me with both Godot Physics and Jolt.

yes, well i logged two additional transformations of the `angular_velocity `cus for some reason when i tried only using global space for torque and logging just the angular_velocity they didnt really match up (meaning that even tho i applied torque on one axis other axises were affected too in the angular_velocity logged)


It seems it works tho, may I have one last question tho. Does both `angular_velocity` and `apply_torque()` use Euler angles? And if I understand correctly, both use the global space.

**Comment by mihe** [comment]
> theres tiny precision errors when the angular velocity gets really high but i guess thats normal(?)

Yes and yes. :)

> Does both `angular_velocity` and `apply_torque()` use Euler angles? And if I understand correctly, both use the global space.

The `angular_velocity` is the amount of radians per second (clockwise) around that particular axis. `apply_torque` is specified in [Newton-metre](https://en.wikipedia.org/wiki/Newton-metre).

They're both in global-space, yes.

**Comment by TrogerMester** [comment]
alright thanks a lot i was just really confused cus the docs dont really specify these stuff
