### ISSUE TITLE
Some things aren't working when using godot-jolt

### ISSUE THREAD

**Issue by v6stXN46WdLBtp** [godot-jolt/godot-jolt#946]
I am sorry for the lack of information in this issue but I am having trouble dissecting the issue. When using godot's default physics rocket jumping works fine. But when using godot-jolt 0.13.0 rocket jumping fails when just standing and shooting at the ground or anywhere close.

I believe this issue somehow occurs in the `apply_knockback` function located in `explosion.gd`. 

This is the project in question https://github.com/Mickeon/team-fortress-jumper

**Comment by mihe** [comment]
Without looking too closely at that project, I would be prepared to guess that you're likely running into the issue mentioned [here](https://github.com/godot-jolt/godot-jolt?tab=readme-ov-file#what-else-is-different) about the ray-cast parameter `hit_back_faces` behaving differently in Godot Jolt compared to Godot Physics.

Basically the `query` [here](https://github.com/Mickeon/team-fortress-jumper/blob/feacc9264bd5272668790d54bf75a4183e38b748/wep/other/explosion.gd#L108-L110) likely just needs to have `query.hit_back_faces = false` set.

**Comment by v6stXN46WdLBtp** [comment]
That was the solution. Closing.
