### ISSUE TITLE
`PhysicsDirectBodyState3D.center_of_mass` should be a relative global position

### ISSUE THREAD

**Issue by MajorMcDoom** [godot-jolt/godot-jolt#947]
`PhysicsDirectBodyState3D.center_of_mass` is returning the center of mass as an *absolute world position*, whereas Godot physics and the Godot docs report it as a *world-space offset from the body's transform origin*.

You can repro this in any project with a `RigidBody3D` that has imbalanced colliders and isn't placed at the world origin. Print out its `PhysicsDirectBodyState3D.center_of_mass` (you'll have to wait until after the first frame for Godot physics). Depending on which physics extension you use, the vector will be different.

**Comment by MajorMcDoom** [comment]
@mihe You can test it on the hammer in the `hammer_test` scene I sent you earlier.

**Comment by mihe** [comment]
That is a bummer. I'm not sure how that went unnoticed for so long.

`center_of_mass_local` seems to work the same though, so I guess you can transform that one for the time being, if you need to be able to jump between the two engines.

**Comment by mihe** [comment]
Thanks for reporting it by the way! Please report any other discrepancies you spot, however small.

**Comment by MajorMcDoom** [comment]
> Thanks for reporting it by the way! Please report any other discrepancies you spot, however small.

Thanks!
