### ISSUE TITLE
The substitute joints don't support changing transform in `_ready`

### ISSUE THREAD

**Issue by JayTThib** [godot-jolt/godot-jolt#959]
Hi, I'm trying to use a `JoltConeTwistJoint3D` to have a `RigidBody3D` swing around another `RigidBody3D`. I figured I could change the angle of the swing by setting the joint's `global_rotation_degrees`, but it seems like I can only get it to work by setting the `rotation` property in the inspector, not through GDScript. I've also tried calling `force_update_transform` on the joint after setting its `global_rotation_degrees`, and that didn't seem to change the swing angle either. Should I be doing something else instead? This doesn't seem like the intended behavior unless I'm misunderstanding how to use joints. 

I'm using Godot 4.3.stable.mono and Jolt 0.13.0-stable. 

Here's a [video](https://youtu.be/-hYG1xHdEU4?si=_K7VUhRZ2eWOoYF1) showing what I'm talking about.

**Comment by mihe** [comment]
Do you want to change this in `_ready` specifically, or at some later point, like for example `_physics_process`?

If you only want this in `_ready` specifically then I can probably fix that. There does seem to be a slight discrepancy with where I initialize the joint compared to the default joints.

If you want this somewhere later in the flow, that won't really work, since the joint node itself is (from the simulation's perspective) really only used to figure out the relative start positions of each body. After that the joint node's transform is more or less useless.

**Comment by JayTThib** [comment]
I was planning on setting it during `_integrate_forces` from a player `RigidBody3D` every now and then, but `_ready` would work too (since it looks like I can call `request_ready` to call `_ready` again? I could just add the joint back to the scene when a new swing is started). I'm using the joint to physically swing a sword around the player in a first person game, and the swing angle can change depending on where the player is looking. The direction the player is looking is locked once a swing starts.

**Comment by mihe** [comment]
What you can do also, as a workaround, is to unset the `node_a` and `node_b` properties, change the transform, and then reset `node_a` and `node_b`, which will force the joint to reinitialize, much like if you pulled it from the tree entirely.

I should also point out that if you don't need some of the Jolt-specific properties of `JoltConeTwistJoint3D` (like the motors or limit springs) then you can also just use `ConeTwistJoint3D`, which should support changing the transform in `_ready`. They share the same "backend" with this extension, so there isn't much a difference between them.

**Comment by JayTThib** [comment]
Just tried it and it works! Thanks for the help :)

**Comment by mihe** [comment]
> you can also just use `ConeTwistJoint3D`, which should support changing the transform in `_ready`

It seems I misread the code, and `JoltConeTwistJoint3D` does in fact behave the same as `ConeTwistJoint3D`, which similarly configures the joint on `NOTIFICATION_POST_ENTER_TREE`.

Since there's no discrepancy I'll go ahead and close this.
