### ISSUE TITLE
Springs in Generic6DOFJoint3D get stuck when reaching joint

### ISSUE THREAD

**Issue by RaphaelVI** [godot-jolt/godot-jolt#985]
I created a test scene to try to isolate the issue with the following parameters :

The scene contains two nodes, a sphere and a anchor point that follow the mouse position

![image](https://github.com/user-attachments/assets/2ef8b564-03fb-455b-aca8-ef257287c8b9)

The joint link the anchor, and the sphere 

![image](https://github.com/user-attachments/assets/fa72ca40-8760-42d9-9210-39336d8cc870)

The only Generic6DOFJoint3D parameters activated are Linear Spring, and the values are the following :

![image](https://github.com/user-attachments/assets/290fdccf-488e-4573-be8d-5ca35eb718a6)

Everything is working as intendend

![spring_godot](https://github.com/user-attachments/assets/aef7d86d-7a1b-4b65-a43b-2b7b1f64268a)

But when I stop my mouse, wait for the sphere to stabilize, and try to move again, the sphere appears "stuck" in place, and the springs don't do anything anymore :

![spring_stuck_godot](https://github.com/user-attachments/assets/55eee79c-ccf3-4b11-9702-c102cf450555)

Am I doing something wrong ?

**Comment by mihe** [comment]
Your anchor can't be a `StaticBody3D`, as they are assumed to never move, and won't wake up like dynamic bodies do (i.e. `RigidBody3D`, `AnimatableBody3D` or `CharacterBody3D`). Try making your anchor an `AnimatableBody3D` instead.
