### ISSUE TITLE
Issue With RayCast3D when using direct space state

### ISSUE THREAD

**Issue by hodayfa000-h** [godot-jolt/godot-jolt#988]
hello, so I have encountered issues while using RayCast3D when using Godot-jolt, however this issue does not happen with Godot's default physics engine, here is the code I used to cast a ray from my camera to 500 meters infront of  the camera in gdscript  works with godot's default, but not jolt, here is the main idea of the function:

`func shoot():  
	
	var direct_space = get_world_3d().direct_space_state
	var rayquery = PhysicsRayQueryParameters3D.new()
	rayquery.from = parent.global_position #camera position, camera is parent
	
	rayquery.to = parent.global_position + parent.global_basis.z * -500 #to 500 infront of camera
	rayquery.exclude.append(player)  #ignore player which is defined somewhere
	rayquery.collision_mask = 1 
	
	
	var collision = direct_space.intersect_ray(rayquery)
	if collision and collision.collider is RigidBody3d:
		
		
		var collider = collision.collider as RigidBody3D
		collider.apply_central_impulse(parent.global_basis.z.normalized() * -5) #add impulse to the RigidBody3D in camera's direction
		print(collider)
		
	else:
		print("nothing")	#if we did not hit a Rigidbody3D, print nothing
	
	`

note: i just rechecked by adding a particle to the hit position and found the issue, for SOME REASON it is NOT casting the ray to the 500 range, it is literally casting it too short, just in jolt not in godot... it seems to be hitting something from inside? I added a print and now it says I am colliding with my player, which I tried so hard to fix but same result... even when excluded.

**Comment by hodayfa000-h** [comment]
hey, so turns out hit_back_faces is the issue, i set it to false and now it works

**Comment by mihe** [comment]
This discrepancy has been fixed as of #967. I just need to find the time to cut another release.

If you're able/willing you can also [build from source](https://github.com/godot-jolt/godot-jolt/blob/master/docs/building.md) to get the latest (unreleased) changes.
