### ISSUE TITLE
_rest_info: get_rest_info was passed an invalid transform.

### ISSUE THREAD

**Issue by jijigri** [godot-jolt/godot-jolt#989]
Ever since updating to Godot 4.3 (and updating Godot Jolt accordingly), whenever my player is instantiated, I'm getting spammed by this error:
```
E 0:00:24:0752   _rest_info: get_rest_info was passed an invalid transform. A scale of (1.000000, 1.200000, 1.000000) is not supported by Godot Jolt for this shape/body. The scale will instead be treated as (1.066667, 1.066667, 1.066667).
  <C++ Source>   src\spaces\jolt_physics_direct_space_state_3d.cpp:435 @ _rest_info()

```

![image](https://github.com/user-attachments/assets/a4bfaf1d-8f0c-4c54-80ba-8f3137ce17d2)

This error never happened before updating, and I can't see where it could come from or how I could fix it.

**Comment by mihe** [comment]
Are you using a `ShapeCast3D` node somewhere perhaps? If that was scaled (maybe by some parent node) you would be seeing an error like that.

I realize the error message isn't ideal, but the context from where the error is emitted is very limited unfortunately. I've changed it to at least mention the possibility of `ShapeCast3D`, but haven't been able to cut a new release with that included yet.

**Comment by jijigri** [comment]
Thank you for your help. I do use `ShapeCast3D` nodes in my weapons, but after trying with all weapons completely removed, the error still happens.
Is it possible that using `PhysicsDirectSpaceState3D.intersect_shape()` in a script could lead to this error?
