### ISSUE TITLE
Crash when using `SeparationRayShape3D` in CCD `RigidBody3D`

### ISSUE THREAD

**Issue by TrogerMester** [godot-jolt/godot-jolt#992]
If im not mistaken, the `SeparationRayShape3D` for collision shapes is not properly implemented yet (at least i guess so, based on how buggy it is when colliding with slopes or stairs).

A year ago I read that they dont even work at all, which must have changed, since they do **work**, but get caught up on nearly anything. There was an update on it in 0.13.0, which makes me assume that it is not something thats just not supposed to be used at all(?).

My question is, is `SeparationRayShape3D` planned to be properly implemented in the near future or is it simply something thats not gonna get worked on for a while now.

(I'm curious cus when it comes to creating good locomotion, climbing up strairs and various low obsticles with ease can be pretty challenging to code right and might even be expensive if many active bodies are in the scene. `SeparationRayShape3D`s make such implementation much, much easier and straightforward)

**Comment by mihe** [comment]
> at least i guess so, based on how buggy it is when colliding with slopes or stairs

Feel free to share these bugs and I can take a look at them, ideally as some sort of minimal repro project that I can test/debug for myself.

The current implementation should line up with the implementation in Godot Physics, as far as I'm aware. It's not a terribly complicated shape. It's effectively just a ray-cast pretending to be a convex shape, with the only real gotcha being the `slide_on_slope` parameter, which just changes the reported collision normal.

> A year ago I read that they dont even work at all, which must have changed, since they do **work**, but get caught up on nearly anything. There was an update on it in 0.13.0, which makes me assume that it is not something thats just not supposed to be used at all(?).

It's been fully implemented since the first release of this extension, and I haven't really changed it much since I first implemented it, besides the change in 0.13.0 that you mentioned (#762), which just changed how the shape behaves when enveloped by another convex shape.

> I'm curious cus when it comes to creating good locomotion, climbing up strairs and various low obsticles with ease can be pretty challenging to code right and might even be expensive if many active bodies are in the scene. `SeparationRayShape3D`s make such implementation much, much easier and straightforward

I'll admit I haven't battle-tested the shape much myself, but I've seen people use it for things like stair-stepping in projects of their own, and given that I haven't had any issue reports about it (besides what #762 addressed) I'm assuming it's working well for them.

**Comment by mihe** [comment]
Thank you for the comprehensive repro.

I see you're using it for a `RigidBody3D` character, and with CCD on top of that. That might very well be some uncharted waters.

CCD in particular will not work with `SeparationRayShape3D` at the moment. The reason for this is simply that it's effectively an infinitely thin shape, with no reasonable inner volume/radius that can be used to do the CCD sweep test. This holds true for Godot Physics as well, which just no-ops the CCD implementation for `SeparationRayShape3D`, as seen [here](https://github.com/godotengine/godot/blob/2e144928793f17ebd70e1475bb7a7f4fd1095484/modules/godot_physics_3d/godot_shape_3d.cpp#L180-L182).

With that said, it should obviously not crash the simulation when enabled, so I'll need to take a look at that, but I'm not sure there's much I can do to make it function as you'd probably want it to.

**Comment by TrogerMester** [comment]
> With that said, it should obviously not crash the simulation when enabled, so I'll need to take a look at that, but I'm not sure there's much I can do to make it function as you'd probably want it to.

The reason I had turned on CCD is because in my game there are instances, where the player character could reach high velocities and I fear they might phase through thin walls or miss smaller objects. Since the `SeparationRayShape3D` is mostly used for climbing stairs and stuff I dont even expect it to make my character stop when it collides with something (since when walking they just "teleport" on top of them seemlessly aswell without any change in velocity).

Unfortunately, you can't selectively enable CCD on some shapes and disable on others (just like how you can't set different collision layers and masks for each shape separately, which to be honest would be a great addition to the engine but i guess thats off topic for this issue).

Therefore in my oppinion, what should happen is that when using CCD on a body, the `SeparationRayShape3D` should be omitted from the CCD calculations, it should behave how it does without CCD. If my character's `SeparationRayShape3D` phases through an object at high velocities I can't really get mad since it's not supposed to collide with objects the same way other shapes do (you would just get pushed away by some amount anyways instead of getting an actual collision like if it had volume, `SeparationRayShape3D` won't affect your linear velocity directly anyways as far as I'm aware).

**Comment by mihe** [comment]
The fix for this can now be found in the newly released [0.14.0-stable](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.14.0-stable) release.

Note that the release on Godot Asset Library is still pending approval, so you might need to download it from GitHub for the time being.
