### ISSUE TITLE
VehicleBody3D slides down the slope

### ISSUE THREAD

**Issue by dgsdestinygamestudios** [godot-jolt/godot-jolt#994]
Steps to reproduce:
1- Download truck town demo (or any other car-related demo).
2- Select any vehicle.
3- Drive towards a slope and stop the vehicle.

Expected behaviour:
VehicleBody3D standing still on the slope.

Actual behaviour:
VehicleBody3D sliding down the slope until it reaches a point where what's under it is perfectly flat.

Present in both GodotPhysics and Godot Jolt.

Since I assume this is physics related, if you guys can find a way to fix it, it would be much appreciated.
Tried Unity and Unreal, vehicles stand still on a slope.
Also tried linear and angular damping with no success.

**Comment by mihe** [comment]
> Present in both GodotPhysics and Godot Jolt.

This issue should be reported to the Godot repository in this case. It's not something I can address from this extension.
