### ISSUE TITLE
Soft Body doesn't work from one computer to the next when export ??!

### ISSUE THREAD

**Issue by FrancisJasm** [godot-jolt/godot-jolt#996]
Hi,

I have created my first game with Godot using Jolt.

It is a simple game where the user control a board and need to collect coins.

Unfortunately, for some reasons, when I export my game it is working on my "main" computer (the one where I have Godot install). But when I try to open my game on another computer, then the softbodyball doesn't work !!

-My main computer have a rtx 3070, the other one a gtx 1060... So noting special. 

**I have recorded a video so that it is clear.** As you can see, the ball is working fine on first computer, but it is not in the second one.

https://youtu.be/zusHTUwd95w?si=xG5uYU6wJpu7s5e3

I have try to export with many setting (all, scene, asset, pck, pck embedded, etc...) but that is not resolving the issues...
So it seem I have something install on my main computer that is not on others :D 

If you could help me resolve the issue so I can show my game to my family, that would be much appreciated :-)

**Comment by mihe** [comment]
There's not a whole lot to go by here, so I'm not sure how much help I can be, unfortunately.

My best guess would be that you for whatever reason end up using different physics engines on different machines, perhaps by not bundling the Godot Jolt libraries on one of the machines, causing it to fall back to using Godot Physics instead.
